name: GitHub Pages Deployment (Static Files)

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      # ============================================
      # SASS COMPILATION
      # ============================================
      - name: 📦 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 🎨 Build CSS from Sass (Root)
        run: |
          echo "📁 Building root Sass..."
          cd 3.sass/0.json
          npm install
          npm run sass:build
          cd ../..
          echo "✅ Root style.css created"
          ls -lh style.css

      - name: 🎨 Build CSS from Sass (cv_web)
        run: |
          echo "📁 Building cv_web Sass..."
          cd cv_web/3.sass/0.json
          npm install
          npm run sass:build
          cd ../../..
          echo "✅ cv_web/style.css created"
          ls -lh cv_web/style.css

      # ============================================
      # MYFEED VUE APP BUILD
      # ============================================
      - name: 🚀 Build MyFeed Vue Application
        run: |
          echo "📁 Building MyFeed Vue app..."
          cd myfeed
          npm install
          npm run build
          cd ..
          echo "✅ MyFeed production build created"
          ls -lh myfeed/dist/

      # ============================================
      # MYPROFILE SVELTEKIT APP BUILD
      # ============================================
      - name: 🎮 Build MyProfile SvelteKit Application
        run: |
          echo "📁 Building MyProfile SvelteKit app..."
          cd myprofile/1.1.ops
          chmod +x build.sh
          ./build.sh
          cd ../..
          echo "✅ MyProfile production build created"
          ls -lh myprofile/1.3.svelte/build/
        env:
          NODE_ENV: production

      # ============================================
      # JEKYLL BLOG BUILD
      # ============================================
      - name: 💎 Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false

      - name: 📦 Install Jekyll
        run: |
          gem install jekyll bundler

      - name: 🔨 Build Blog HTML (Jekyll)
        run: |
          cd blog/1.ops
          chmod +x build.sh
          ./build.sh build
          echo "✅ Blog HTML files generated and copied to blog/ directory"

      - name: 🌐 Setup Pages Environment
        uses: actions/configure-pages@v5

      - name: 📂 Prepare Site for Deployment
        run: |
          echo "📋 Creating _site directory and copying all files..."
          mkdir -p _site

          # Copy root files
          echo "Copying root HTML, CSS, and JS files..."
          cp -v index.html _site/ 2>/dev/null || true
          cp -v *.css _site/ 2>/dev/null || true
          cp -v *.js _site/ 2>/dev/null || true

          # Copy static directories
          echo "Copying static directories..."
          cp -r linktree _site/ 2>/dev/null || true
          cp -r cv_web _site/ 2>/dev/null || true
          cp -r cv_pdf _site/ 2>/dev/null || true
          cp -r assets _site/ 2>/dev/null || true
          cp -r others _site/ 2>/dev/null || true

          # Copy MyFeed Vue app build
          echo "Copying MyFeed app..."
          mkdir -p _site/myfeed
          cp -r myfeed/dist/* _site/myfeed/
          echo "✅ MyFeed deployed to _site/myfeed/"
          ls -lah _site/myfeed/

          # Copy MyProfile SvelteKit app build
          echo "Copying MyProfile app..."
          mkdir -p _site/myprofile
          cp -r myprofile/1.3.svelte/build/* _site/myprofile/
          echo "✅ MyProfile deployed to _site/myprofile/"
          ls -lah _site/myprofile/

          # Copy blog directory (includes both .md and .html files)
          echo "Copying blog directory..."
          mkdir -p _site/blog
          cp -r blog/* _site/blog/

          # Clean up source files from deployment (keep only HTML)
          echo "Cleaning up source files..."
          find _site/blog -name "*.md" -type f -delete
          rm -f _site/blog/_config.yml
          rm -f _site/blog/build.sh
          rm -rf _site/blog/_layouts
          rm -rf _site/blog/.jekyll-cache

          echo "✅ All files prepared for deployment"
          echo "📋 Final site structure:"
          ls -lah _site/
          echo "📋 Blog directory (HTML only):"
          ls -lah _site/blog/ || true

      - name: ⬆️ Upload Site Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🚀 Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
