# Jekyll configuration for blog
title: Diego's Blog
description: Blog posts and articles

# Build settings
markdown: kramdown

# No plugins needed
plugins: []

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - "index.html"  # Exclude generated HTML files (not layouts!)
  - 0.spec/       # Specifications directory
  - 1.ops/        # Operations scripts directory
  - 2.assets/     # Assets directory (if not needed by Jekyll)
  - 3.sass/       # Sass source files directory
  - 4.jenkyls/    # Jekyll configuration directory (prevent recursion)
