#!/bin/sh
# deploy.sh — Scan all build.json projects, merge deps into root package.json
# Used by CI (GitHub Actions) and locally to ensure all deps are available
set -e

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"

# ─── GENERATE ROOT PACKAGE.JSON ────────────────────────────
# Reads every project's package.json, merges all deps into one root package.json
generate_package_json() {
    node -e "
const fs = require('fs');
const path = require('path');
const glob = require('child_process')
    .execSync('find . -maxdepth 3 -name build.json -not -path ./build.json', {cwd: '$REPO_ROOT'})
    .toString().trim().split('\n').filter(Boolean);

const deps = {};
const devDeps = {};

for (const bjson of glob) {
    const dir = path.join('$REPO_ROOT', path.dirname(bjson));
    const pkgPath = path.join(dir, 'package.json');
    if (!fs.existsSync(pkgPath)) continue;

    const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
    Object.entries(pkg.dependencies || {}).forEach(([k, v]) => {
        if (!deps[k] || v > deps[k]) deps[k] = v;
    });
    Object.entries(pkg.devDependencies || {}).forEach(([k, v]) => {
        if (!devDeps[k] || v > devDeps[k]) devDeps[k] = v;
    });
}

// Sort keys
const sort = obj => Object.fromEntries(Object.entries(obj).sort(([a],[b]) => a.localeCompare(b)));

const root = {
    name: 'front-monorepo',
    private: true,
    description: 'Auto-generated by deploy.sh — merged deps from all projects',
    dependencies: sort(deps),
    devDependencies: sort(devDeps)
};

fs.writeFileSync(path.join('$REPO_ROOT', 'package.json'), JSON.stringify(root, null, 2) + '\n');
const total = Object.keys(deps).length + Object.keys(devDeps).length;
console.log('package.json: ' + total + ' packages (' + Object.keys(deps).length + ' deps + ' + Object.keys(devDeps).length + ' devDeps)');
" 2>/dev/null || python3 -c "
import json, os, glob as g

repo = '$REPO_ROOT'
deps, dev = {}, {}

for bjson in g.glob(os.path.join(repo, '*', '*', 'build.json')) + g.glob(os.path.join(repo, '*', 'build.json')):
    d = os.path.dirname(bjson)
    pkg = os.path.join(d, 'package.json')
    if not os.path.exists(pkg): continue
    p = json.load(open(pkg))
    for k, v in p.get('dependencies', {}).items():
        if k not in deps or v > deps[k]: deps[k] = v
    for k, v in p.get('devDependencies', {}).items():
        if k not in dev or v > dev[k]: dev[k] = v

root = {
    'name': 'front-monorepo',
    'private': True,
    'description': 'Auto-generated by deploy.sh -- merged deps from all projects',
    'dependencies': dict(sorted(deps.items())),
    'devDependencies': dict(sorted(dev.items()))
}

with open(os.path.join(repo, 'package.json'), 'w') as f:
    json.dump(root, f, indent=2)
    f.write('\n')
total = len(deps) + len(dev)
print(f'package.json: {total} packages ({len(deps)} deps + {len(dev)} devDeps)')
"
}

# ─── BUILD ALL CHANGED PROJECTS ────────────────────────────
build_all() {
    local failed="" passed=0 skipped=0 errors=0

    for bjson in $(find "$REPO_ROOT" -maxdepth 3 -name "build.json" -not -path "$REPO_ROOT/build.json" | sort); do
        local dir="$(dirname "$bjson")"
        local name="$(basename "$dir")"
        local parent="$(basename "$(dirname "$dir")")"
        local label="$parent/$name"

        if [ ! -f "$dir/build.sh" ]; then
            skipped=$((skipped + 1))
            continue
        fi

        printf "\n\033[0;34m▶\033[0m Building %s...\n" "$label"
        if (cd "$dir" && bash build.sh build); then
            passed=$((passed + 1))
        else
            errors=$((errors + 1))
            failed="$failed $label"
        fi
    done

    echo ""
    echo "========================================"
    echo "  Passed: $passed  Failed: $errors  Skipped: $skipped"
    [ -n "$failed" ] && echo "  FAILED:$failed"
    echo "========================================"
    [ $errors -eq 0 ]
}

# ─── CLI ───────────────────────────────────────────────────
case "${1:-deps}" in
    deps)
        echo "Scanning projects and generating root package.json..."
        generate_package_json
        echo "Installing dependencies..."
        cd "$REPO_ROOT" && npm install --no-fund --no-audit --legacy-peer-deps
        echo "Done."
        ;;
    build)
        build_all
        ;;
    all)
        echo "=== Phase 1: Dependencies ==="
        generate_package_json
        cd "$REPO_ROOT" && npm install --no-fund --no-audit --legacy-peer-deps
        echo ""
        echo "=== Phase 2: Build ==="
        build_all
        ;;
    *)
        echo "Usage: ./deploy.sh [deps|build|all]"
        echo "  deps   Merge all project deps into root package.json + npm install (default)"
        echo "  build  Build all projects"
        echo "  all    deps + build"
        ;;
esac
