
// this file is generated — do not edit it


/// <reference types="@sveltejs/kit" />

/**
 * Environment variables [loaded by Vite](https://vitejs.dev/guide/env-and-mode.html#env-files) from `.env` files and `process.env`. Like [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), this module cannot be imported into client-side code. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * _Unlike_ [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), the values exported from this module are statically injected into your bundle at build time, enabling optimisations like dead code elimination.
 * 
 * ```ts
 * import { API_KEY } from '$env/static/private';
 * ```
 * 
 * Note that all environment variables referenced in your code should be declared (for example in an `.env` file), even if they don't have a value until the app is deployed:
 * 
 * ```
 * MY_FEATURE_FLAG=""
 * ```
 * 
 * You can override `.env` values from the command line like so:
 * 
 * ```sh
 * MY_FEATURE_FLAG="enabled" npm run dev
 * ```
 */
declare module '$env/static/private' {
	export const SHELL: string;
	export const npm_command: string;
	export const COREPACK_ENABLE_AUTO_PIN: string;
	export const aa_sui_radicale_secrets__RADICALE_USERS: string;
	export const SESSION_MANAGER: string;
	export const bc_obs_ntfy_secrets__NTFY_USER_PASSWORD: string;
	export const WINDOWID: string;
	export const SSH_S21_RSA_PUB: string;
	export const bc_obs_c3_infra_api_secrets__CF_API_KEY: string;
	export const __ETC_PROFILE_DONE: string;
	export const ca_dat_db_agent_secrets__NTFY_URL: string;
	export const npm_config_userconfig: string;
	export const bc_obs_nocodb_secrets__NC_ADMIN_EMAIL: string;
	export const JUPYTER_CONFIG_DIR: string;
	export const __HM_SESS_VARS_SOURCED: string;
	export const COLORTERM: string;
	export const GTK_THEME: string;
	export const bc_obs_dagu_secrets__OCI_S3_SECRET_KEY: string;
	export const aa_sui_tools_stalwart_secrets__DKIM_PRIVATE_KEY_B64: string;
	export const aa_sui_mattermost_bots_secrets__MM_CLAUDE_PASSWORD: string;
	export const XDG_CONFIG_DIRS: string;
	export const RESEND_API_KEY: string;
	export const npm_config_cache: string;
	export const aa_sui_mattermost_mcp_secrets__MM_ADMIN_USERNAME: string;
	export const LESS: string;
	export const CRAWLEE_API_TOKEN: string;
	export const ca_dat_backup_bup_secrets__MYSQL_USER: string;
	export const XDG_SESSION_PATH: string;
	export const XDG_MENU_PREFIX: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_CC_SECRET: string;
	export const AUTHELIA_OIDC_CLIENT_ID: string;
	export const aa_sui_google_workspace_mcp_secrets__GOOGLE_SERVICE_ACCOUNT_KEY: string;
	export const SPEECHD_CMD: string;
	export const ca_dat_backup_bup_secrets__MYSQL_HOST: string;
	export const WG_PRIVATE_KEY: string;
	export const aa_sui_mattermost_mcp_secrets__MM_CLAUDE_PASSWORD: string;
	export const AI_AGENT: string;
	export const OCI_S3_REGION: string;
	export const bc_obs_windmill_secrets__SMTP_USERNAME: string;
	export const bc_obs_windmill_secrets__SMTP_PORT: string;
	export const NOCODB_ADMIN_EMAIL: string;
	export const MOZ_X11_EGL: string;
	export const bc_obs_nocodb_secrets_powersheets__POSTGRES_PASSWORD: string;
	export const ICEAUTHORITY: string;
	export const vps_resend_secrets__cloudflare_zone_id: string;
	export const LANGUAGE: string;
	export const aa_sui_mattermost_mcp_secrets__MM_URL: string;
	export const OCI_USER_OCID: string;
	export const NODE: string;
	export const ab_mic_vaultwarden_secrets__SMTP_PASSWORD: string;
	export const ca_dat_backup_bup_secrets__PGPASSWORD: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_DB: string;
	export const bc_obs_matomo_secrets__MYSQL_ROOT_PASSWORD: string;
	export const LESS_TERMCAP_se: string;
	export const bc_obs_c3_services_mcp_secrets__DAGU_BASIC_AUTH: string;
	export const LESS_TERMCAP_so: string;
	export const ca_dat_backup_bup_secrets__SQLITE_DBS: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_SECRET: string;
	export const CLOUDFLARE_EMAIL: string;
	export const QT_LOGGING_RULES_DEFAULT_PRESENT: string;
	export const QT_LOGGING_RULES: string;
	export const ANTHROPIC_API_KEY: string;
	export const XDG_DATA_HOME: string;
	export const PROFILE: string;
	export const C3_API_KEY: string;
	export const MOZ_DRM_DEVICE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SECRET: string;
	export const WG_GCP_PROXY_PRIVATE_KEY: string;
	export const bb_sec_caddy_secrets__AUTHELIA_CLI_SECRET: string;
	export const ac_fin_crawlee_cloud_secrets__RUNNER_TOKEN: string;
	export const aa_sui_photoprism_secrets__MARIADB_USER: string;
	export const SHELL_SESSION_ID: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUDFLARE_SECRET: string;
	export const XDG_CONFIG_HOME: string;
	export const aa_sui_mail_mcp_secrets__MAIL_PASSWORD: string;
	export const XCURSOR_PATH: string;
	export const MEMORY_PRESSURE_WRITE: string;
	export const bc_obs_windmill_secrets__DB_PASSWORD: string;
	export const bc_obs_c3_infra_mcp_secrets__C3_API_KEY: string;
	export const aa_sui_photoprism_secrets__MARIADB_PASSWORD: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_AUTH_JWT_SECRET: string;
	export const COLOR: string;
	export const OPENAI_API_KEY: string;
	export const LOCALE_ARCHIVE_2_27: string;
	export const npm_config_local_prefix: string;
	export const WG_OCI_APPS_PRIVATE_KEY: string;
	export const LIBVA_DRIVER_NAME: string;
	export const GNUPGHOME: string;
	export const DESKTOP_SESSION: string;
	export const bb_sec_authelia_secrets__AUTHELIA_JWT_SECRET: string;
	export const LC_MONETARY: string;
	export const aa_sui_mattermost_bots_secrets__AUTHELIA_OIDC_MATTERMOST_SECRET: string;
	export const GDK_PIXBUF_MODULE_FILE: string;
	export const ca_dat_backup_bup_secrets__MYSQL_DBS: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_PASSWORD: string;
	export const ca_dat_db_agent_secrets__BUP_REMOTE: string;
	export const GTK_RC_FILES: string;
	export const npm_config_globalconfig: string;
	export const GPG_TTY: string;
	export const OCI_SSH_KEY: string;
	export const EDITOR: string;
	export const aa_sui_tools_stalwart_secrets__CF_DNS_API_TOKEN: string;
	export const ca_dat_db_agent_secrets__NTFY_TOPIC: string;
	export const FZF_ALT_C_OPTS: string;
	export const ab_mic_vaultwarden_secrets__SMTP_USERNAME: string;
	export const bc_obs_umami_secrets__DB_PASSWORD: string;
	export const XDG_SEAT: string;
	export const CARGO_TARGET_DIR: string;
	export const aa_sui_photoprism_secrets__OCI_S3_ACCESS_KEY: string;
	export const bc_obs_c3_infra_mcp_secrets__RESEND_API_KEY: string;
	export const OPENAI_BASE_URL: string;
	export const OCI_REGION: string;
	export const NAUTILUS_4_EXTENSION_DIR: string;
	export const PWD: string;
	export const XDG_VIDEOS_DIR: string;
	export const NIX_PROFILES: string;
	export const aa_sui_photoprism_secrets__OCI_S3_SECRET_KEY: string;
	export const NIX_GSETTINGS_OVERRIDES_DIR: string;
	export const LOGNAME: string;
	export const XDG_SESSION_DESKTOP: string;
	export const QT_QPA_PLATFORMTHEME: string;
	export const XDG_SESSION_TYPE: string;
	export const ca_dat_backup_bup_secrets__POSTGRES_DBS: string;
	export const TF_VAR_tenancy_ocid: string;
	export const ca_dat_kg_graph_secrets__SURREAL_ROOT_PASSWORD: string;
	export const WG_OCI_APPS_PUBLIC_KEY: string;
	export const NIX_PATH: string;
	export const home_manager__shared_secrets__GCP_COMPUTE_ENGINE: string;
	export const npm_config_init_module: string;
	export const SYSTEMD_EXEC_PID: string;
	export const NIXPKGS_CONFIG: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__MM_BOT_TOKEN: string;
	export const _: string;
	export const ca_dat_redis_secrets__REDIS_PASSWORD: string;
	export const aa_sui_mattermost_mcp_secrets__CLAUDE_MODEL: string;
	export const XAUTHORITY: string;
	export const ab_mic_vaultwarden_secrets__ADMIN_TOKEN: string;
	export const bc_obs_c3_infra_mcp_secrets__DAGU_PASSWORD: string;
	export const XDG_PICTURES_DIR: string;
	export const NoDefaultCurrentDirectoryInExePath: string;
	export const WG_OCI_ANALYTICS_PRIVATE_KEY: string;
	export const FZF_DEFAULT_COMMAND: string;
	export const MOZ_WEBRENDER: string;
	export const WG_TERMUX_PRIVATE_KEY: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_DB: string;
	export const TF_PLUGIN_CACHE_DIR: string;
	export const bc_obs_c3_infra_api_secrets__C3_API_KEY: string;
	export const bc_obs_c3_infra_mcp_secrets__MM_BOT_TOKEN: string;
	export const OCI_S3_ENDPOINT: string;
	export const ca_dat_backup_borg_secrets__SOURCE_DIRS: string;
	export const CLAUDECODE: string;
	export const ac_fin_crawlee_cloud_secrets__ADMIN_PASSWORD: string;
	export const OCI_TENANCY_OCID: string;
	export const AUTHELIA_JWKS_PUBLIC_KEY: string;
	export const aa_sui_mattermost_mcp_secrets__MM_TEAM_ID: string;
	export const WG_LOCAL_IP: string;
	export const XKB_DEFAULT_MODEL: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
	export const GTK2_RC_FILES: string;
	export const ab_mic_vaultwarden_secrets__SMTP_PORT: string;
	export const bc_obs_c3_infra_api_secrets__DAGU_USERNAME: string;
	export const NIXPKGS_QT6_QML_IMPORT_PATH: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NOCODB_SECRET: string;
	export const HOME: string;
	export const XDG_PUBLICSHARE_DIR: string;
	export const WG_OCI_MAIL_PUBLIC_KEY: string;
	export const SSH_ASKPASS: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SONNET_SECRET: string;
	export const LANG: string;
	export const bb_sec_caddy_secrets__NTFY_ADMIN_AUTH: string;
	export const TMUX_TMPDIR: string;
	export const GITHUB_TOKEN: string;
	export const aa_sui_tools_stalwart_secrets__AWS_RELAYPASSWORD: string;
	export const GCP_T4_SSH_KEY: string;
	export const FZF_CTRL_R_OPTS: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_C3_MCP_SECRET: string;
	export const XDG_CURRENT_DESKTOP: string;
	export const CARGO_HOME: string;
	export const KONSOLE_DBUS_SERVICE: string;
	export const npm_package_version: string;
	export const bc_obs_umami_secrets__ADMIN_USERNAME: string;
	export const ca_dat_backup_bup_secrets__PGUSER: string;
	export const OCI_S3_BUCKET: string;
	export const bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_PASSWORD: string;
	export const MEMORY_PRESSURE_WATCH: string;
	export const STARSHIP_SHELL: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_USER: string;
	export const OCI_S3_SECRET_KEY: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_ADMIN_EMAIL: string;
	export const SSH_S21_ED25519_PUB: string;
	export const WAYLAND_DISPLAY: string;
	export const NOCODB_API_TOKEN: string;
	export const vps_resend_secrets__cloudflare_api_token: string;
	export const ba_clo_cloudflare_secrets__cloudflare_api_key: string;
	export const KONSOLE_DBUS_SESSION: string;
	export const PROFILEHOME: string;
	export const WG_HUB_IP: string;
	export const GIO_EXTRA_MODULES: string;
	export const bc_obs_windmill_secrets__SMTP_PASSWORD: string;
	export const XDG_DOWNLOAD_DIR: string;
	export const SOPS_AGE_KEY: string;
	export const WG_OCI_ANALYTICS_PUBLIC_KEY: string;
	export const HM_PROFILE: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_DB: string;
	export const aa_sui_mattermost_bots_secrets__MM_SQLSETTINGS_DATASOURCE: string;
	export const bc_obs_dagu_secrets__DAGU_USERNAME: string;
	export const XDG_SEAT_PATH: string;
	export const home_manager__shared_secrets__VAULT_ID_RSA: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_ADMIN_PASSWORD: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_PASSWORD: string;
	export const aa_sui_tools_stalwart_secrets__ADMIN_PASSWORD: string;
	export const CF_API_KEY: string;
	export const XDG_MUSIC_DIR: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_EMAIL: string;
	export const NOCODB_URL: string;
	export const home_manager__shared_secrets__SURFACE_DEPLOY_PUB: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_HAIKU_SECRET: string;
	export const AUTHELIA_OIDC_CREDENTIALS_DIR: string;
	export const GCP_PROXY_SSH_KEY_PUB: string;
	export const XDG_TEMPLATES_DIR: string;
	export const aa_sui_tools_smtp_proxy_secrets__API_KEY: string;
	export const INVOCATION_ID: string;
	export const bc_obs_nocodb_secrets__POSTGRES_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_STORAGE_ENCRYPTION_KEY: string;
	export const ac_fin_crawlee_cloud_secrets__JWT_SECRET: string;
	export const KONSOLE_VERSION: string;
	export const aa_sui_tools_stalwart_secrets__AWS_RELAYUSER: string;
	export const vps_resend_secrets__resend_api_key: string;
	export const MANAGERPID: string;
	export const home_manager__shared_secrets__GCP_COMPUTE_ENGINE_PUB: string;
	export const PIP_CACHE_DIR: string;
	export const GCP_SERVICE_ACCOUNT_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_SECRET: string;
	export const home_manager__shared_secrets__ID_ED25519: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_USER: string;
	export const bc_obs_c3_infra_mcp_secrets__CF_API_EMAIL: string;
	export const GPG_PRIVATE_KEY: string;
	export const INIT_CWD: string;
	export const home_manager__shared_secrets__VAULT_ID_RSA_PUB: string;
	export const bc_obs_nocodb_secrets__NC_ADMIN_PASSWORD: string;
	export const bc_obs_windmill_secrets__OAUTH_CLIENT_SECRET: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_USERNAME: string;
	export const STARSHIP_SESSION_KEY: string;
	export const ac_fin_crawlee_cloud_secrets__MINIO_PASSWORD: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_USER: string;
	export const KDE_SESSION_UID: string;
	export const MOZ_DISABLE_RDD_SANDBOX: string;
	export const WG_OCI_MAIL_PRIVATE_KEY: string;
	export const bc_obs_c3_services_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
	export const XDG_CACHE_HOME: string;
	export const home_manager__shared_secrets__SURFACE_NIXOS_PUB: string;
	export const NIX_USER_PROFILE_DIR: string;
	export const INFOPATH: string;
	export const npm_lifecycle_script: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_PASSWORD: string;
	export const aa_sui_tools_stalwart_secrets__OCI_RELAYPASSWORD: string;
	export const ac_fin_crawlee_cloud_secrets__ADMIN_EMAIL: string;
	export const aa_sui_code_server_secrets__sudo_password: string;
	export const bc_obs_nocodb_secrets__NC_OIDC_CLIENT_SECRET: string;
	export const ab_mic_vaultwarden_secrets__SMTP_HOST: string;
	export const XKB_DEFAULT_LAYOUT: string;
	export const bc_obs_c3_infra_mcp_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_URL: string;
	export const OCI_API_KEY_PUB: string;
	export const npm_config_npm_version: string;
	export const ca_dat_backup_borg_secrets__BORG_PASSPHRASE: string;
	export const WG_GCP_PROXY_PUBLIC_KEY: string;
	export const XDG_SESSION_CLASS: string;
	export const XDG_DESKTOP_DIR: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_USER: string;
	export const GIT_BASE: string;
	export const CLOUDFLARE_API_KEY: string;
	export const PYTHONPATH: string;
	export const aa_sui_snappymail_secrets__SNAPPYMAIL_ADMIN_PASSWORD: string;
	export const TERM: string;
	export const ab_mic_vaultwarden_secrets__SMTP_SECURITY: string;
	export const npm_package_name: string;
	export const bc_obs_c3_infra_api_secrets__DAGU_PASSWORD: string;
	export const LESS_TERMCAP_mb: string;
	export const TF_VAR_compartment_ocid: string;
	export const FZF_CTRL_T_COMMAND: string;
	export const LESS_TERMCAP_me: string;
	export const GTK_PATH: string;
	export const LESS_TERMCAP_md: string;
	export const WG_INTERFACE: string;
	export const WG_SURFACE_PRIVATE_KEY: string;
	export const GPG_PUBLIC_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_SESSION_SECRET: string;
	export const SSH_SURFACE_PRO_ED25519_PUB: string;
	export const npm_config_prefix: string;
	export const bc_obs_umami_secrets__APP_SECRET: string;
	export const LESSOPEN: string;
	export const USER: string;
	export const ab_mic_vaultwarden_secrets__SMTP_FROM: string;
	export const bc_obs_c3_services_mcp_secrets__GITHUB_TOKEN: string;
	export const OCI_S3_ACCESS_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_USER_DIEGO_HASH: string;
	export const FZF_ALT_C_COMMAND: string;
	export const aa_sui_photoprism_secrets__MARIADB_ROOT_PASSWORD: string;
	export const WG_GHA_RUNNER_PUBLIC_KEY: string;
	export const COLORFGBG: string;
	export const ac_fin_crawlee_cloud_secrets__MINIO_USER: string;
	export const TZDIR: string;
	export const QT_WAYLAND_RECONNECT: string;
	export const FZF_CTRL_T_OPTS: string;
	export const aa_sui_tools_smtp_proxy_secrets__LISTEN_PORT: string;
	export const KDE_SESSION_VERSION: string;
	export const PAM_KWALLET5_LOGIN: string;
	export const CF_ZONE_ID: string;
	export const bc_obs_ntfy_secrets__NTFY_ADMIN_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_JWKS_KEY: string;
	export const ca_dat_backup_gitea_secrets__GITEA__security__INTERNAL_TOKEN: string;
	export const MANPAGER: string;
	export const VISUAL: string;
	export const bc_obs_c3_infra_api_secrets__MM_BOT_TOKEN: string;
	export const AUTHELIA_TOKEN_URL: string;
	export const DISPLAY: string;
	export const bb_sec_caddy_secrets__CF_API_TOKEN: string;
	export const npm_lifecycle_event: string;
	export const SHLVL: string;
	export const LESS_TERMCAP_ue: string;
	export const ca_dat_backup_borg_secrets__ARCHIVE_NAME: string;
	export const ca_dat_backup_gitea_secrets__GITEA__oauth2__JWT_SECRET: string;
	export const MOZ_ENABLE_WAYLAND: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_PASSWORD: string;
	export const SSH_SURFACE_PRO_ED25519: string;
	export const LESS_TERMCAP_us: string;
	export const GIT_EDITOR: string;
	export const ca_dat_backup_bup_secrets__PGHOST: string;
	export const __HM_ZSH_SESS_VARS_SOURCED: string;
	export const PAGER: string;
	export const WG_HUB_ENDPOINT: string;
	export const home_manager__shared_secrets__CLAUDE_WEBSERVER_PUB: string;
	export const ca_dat_db_agent_secrets__VM_NAME: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUD_ADMIN_SECRET: string;
	export const QTWEBKIT_PLUGIN_PATH: string;
	export const bc_obs_dagu_secrets__AUTHELIA_OIDC_DAGU_SECRET: string;
	export const TF_VAR_cloudflare_api_key: string;
	export const ca_dat_backup_gitea_secrets__GITEA__security__SECRET_KEY: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_PASSWORD: string;
	export const LC_MEASUREMENT: string;
	export const __NIXOS_SET_ENVIRONMENT_DONE: string;
	export const XDG_VTNR: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_CC_SECRET: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MONITORING_SECRET: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_ROOT_PASSWORD: string;
	export const NOCODB_XC_TOKEN: string;
	export const aa_sui_tools_smtp_proxy_secrets__SMTP_HOST: string;
	export const bc_obs_dagu_secrets__DAGU_PASSWORD: string;
	export const XDG_SESSION_ID: string;
	export const ca_dat_backup_bup_secrets__MYSQL_PASSWORD: string;
	export const LOCALE_ARCHIVE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_REDIS_PASSWORD: string;
	export const SSH_S21_ED25519: string;
	export const ATUIN_SESSION: string;
	export const LESSKEYIN_SYSTEM: string;
	export const npm_config_user_agent: string;
	export const aa_sui_photoprism_secrets__PHOTOPRISM_ADMIN_PASSWORD: string;
	export const QML2_IMPORT_PATH: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_OPUS_SECRET: string;
	export const aa_sui_photoprism_secrets__MARIADB_DATABASE: string;
	export const TERMINFO_DIRS: string;
	export const DEVICE: string;
	export const aa_sui_code_server_secrets__CODE_SERVER_PASSWORD: string;
	export const WG_DNS: string;
	export const XDG_STATE_HOME: string;
	export const npm_execpath: string;
	export const home_manager__shared_secrets__MATOMO_SERVER_PUB: string;
	export const bc_obs_windmill_secrets__SMTP_HOST: string;
	export const bc_obs_c3_infra_api_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
	export const bc_obs_umami_secrets__ADMIN_PASSWORD: string;
	export const CF_API_EMAIL: string;
	export const ad_agi_rig_agentic_hai_1_5bq4_secrets__MM_BOT_TOKEN: string;
	export const aa_sui_tools_stalwart_secrets__NOREPLY_PASSWORD: string;
	export const aa_sui_tools_stalwart_secrets__ME_PASSWORD: string;
	export const bc_obs_c3_infra_mcp_secrets__CF_API_KEY: string;
	export const XDG_RUNTIME_DIR: string;
	export const bc_obs_windmill_secrets__OAUTH_CLIENT_ID: string;
	export const OCI_API_KEY: string;
	export const aa_sui_tools_stalwart_secrets__OCI_RELAYUSER: string;
	export const GCP_T4_SSH_KEY_PUB: string;
	export const GCP_PROXY_SSH_KEY: string;
	export const aa_sui_mattermost_bots_secrets__BEARER_TOKEN: string;
	export const NODE_PATH: string;
	export const CLAUDE_CODE_ENTRYPOINT: string;
	export const CF_DOMAIN: string;
	export const NIX_XDG_DESKTOP_PORTAL_DIR: string;
	export const AUTHELIA_OIDC_TOKENS_DIR: string;
	export const npm_package_json: string;
	export const LC_TIME: string;
	export const aa_sui_mail_mcp_secrets__RESEND_API_KEY: string;
	export const XDG_DOCUMENTS_DIR: string;
	export const bc_obs_nocodb_secrets__NC_AUTH_JWT_SECRET: string;
	export const bc_obs_c3_infra_mcp_secrets__DAGU_USERNAME: string;
	export const bc_obs_c3_infra_api_secrets__RESEND_API_KEY: string;
	export const bc_obs_dagu_secrets__BORG_PASSPHRASE: string;
	export const LC_ALL: string;
	export const OCI_SSH_KEY_PUB: string;
	export const WG_SURFACE_PUBLIC_KEY: string;
	export const QT_AUTO_SCREEN_SCALE_FACTOR: string;
	export const JOURNAL_STREAM: string;
	export const bc_obs_c3_infra_api_secrets__CF_API_EMAIL: string;
	export const XDG_DATA_DIRS: string;
	export const KDE_FULL_SESSION: string;
	export const LIBEXEC_PATH: string;
	export const CLAUDE_CODE_EXECPATH: string;
	export const SSH_S21_RSA: string;
	export const aa_sui_tools_smtp_proxy_secrets__SMTP_PORT: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NPM_SECRET: string;
	export const npm_config_noproxy: string;
	export const PATH: string;
	export const AUTHELIA_JWKS_PRIVATE_KEY: string;
	export const npm_config_node_gyp: string;
	export const __fish_nixos_env_preinit_sourced: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_URL: string;
	export const WGPU_BACKEND: string;
	export const DBUS_SESSION_BUS_ADDRESS: string;
	export const bb_sec_authelia_secrets__AUTHELIA_SMTP_PASSWORD: string;
	export const FZF_DEFAULT_OPTS: string;
	export const bc_obs_dagu_secrets__RESTIC_PASSWORD: string;
	export const npm_config_global_prefix: string;
	export const KDE_APPLICATIONS_AS_SCOPE: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_NAME: string;
	export const KPACKAGE_DEP_RESOLVERS_PATH: string;
	export const aa_sui_mattermost_bots_secrets__POSTGRES_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLI_SECRET: string;
	export const QT_PLUGIN_PATH: string;
	export const OCI_FINGERPRINT: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_USER: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_HMAC_SECRET: string;
	export const TF_VAR_region: string;
	export const aa_sui_mail_mcp_secrets__MAIL_USER: string;
	export const VAULT_DEPLOY_KEY: string;
	export const XKB_DEFAULT_OPTIONS: string;
	export const npm_node_execpath: string;
	export const WG_TERMUX_PUBLIC_KEY: string;
	export const bc_obs_windmill_secrets__SMTP_FROM: string;
	export const bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_USER: string;
	export const LC_NUMERIC: string;
	export const OLDPWD: string;
	export const GOPATH: string;
	export const KONSOLE_DBUS_WINDOW: string;
	export const CF_API_TOKEN: string;
	export const NODE_ENV: string;
}

/**
 * Similar to [`$env/static/private`](https://svelte.dev/docs/kit/$env-static-private), except that it only includes environment variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Values are replaced statically at build time.
 * 
 * ```ts
 * import { PUBLIC_BASE_URL } from '$env/static/public';
 * ```
 */
declare module '$env/static/public' {
	
}

/**
 * This module provides access to runtime environment variables, as defined by the platform you're running on. For example if you're using [`adapter-node`](https://github.com/sveltejs/kit/tree/main/packages/adapter-node) (or running [`vite preview`](https://svelte.dev/docs/kit/cli)), this is equivalent to `process.env`. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * This module cannot be imported into client-side code.
 * 
 * ```ts
 * import { env } from '$env/dynamic/private';
 * console.log(env.DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 * 
 * > [!NOTE] In `dev`, `$env/dynamic` always includes environment variables from `.env`. In `prod`, this behavior will depend on your adapter.
 */
declare module '$env/dynamic/private' {
	export const env: {
		SHELL: string;
		npm_command: string;
		COREPACK_ENABLE_AUTO_PIN: string;
		aa_sui_radicale_secrets__RADICALE_USERS: string;
		SESSION_MANAGER: string;
		bc_obs_ntfy_secrets__NTFY_USER_PASSWORD: string;
		WINDOWID: string;
		SSH_S21_RSA_PUB: string;
		bc_obs_c3_infra_api_secrets__CF_API_KEY: string;
		__ETC_PROFILE_DONE: string;
		ca_dat_db_agent_secrets__NTFY_URL: string;
		npm_config_userconfig: string;
		bc_obs_nocodb_secrets__NC_ADMIN_EMAIL: string;
		JUPYTER_CONFIG_DIR: string;
		__HM_SESS_VARS_SOURCED: string;
		COLORTERM: string;
		GTK_THEME: string;
		bc_obs_dagu_secrets__OCI_S3_SECRET_KEY: string;
		aa_sui_tools_stalwart_secrets__DKIM_PRIVATE_KEY_B64: string;
		aa_sui_mattermost_bots_secrets__MM_CLAUDE_PASSWORD: string;
		XDG_CONFIG_DIRS: string;
		RESEND_API_KEY: string;
		npm_config_cache: string;
		aa_sui_mattermost_mcp_secrets__MM_ADMIN_USERNAME: string;
		LESS: string;
		CRAWLEE_API_TOKEN: string;
		ca_dat_backup_bup_secrets__MYSQL_USER: string;
		XDG_SESSION_PATH: string;
		XDG_MENU_PREFIX: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_CC_SECRET: string;
		AUTHELIA_OIDC_CLIENT_ID: string;
		aa_sui_google_workspace_mcp_secrets__GOOGLE_SERVICE_ACCOUNT_KEY: string;
		SPEECHD_CMD: string;
		ca_dat_backup_bup_secrets__MYSQL_HOST: string;
		WG_PRIVATE_KEY: string;
		aa_sui_mattermost_mcp_secrets__MM_CLAUDE_PASSWORD: string;
		AI_AGENT: string;
		OCI_S3_REGION: string;
		bc_obs_windmill_secrets__SMTP_USERNAME: string;
		bc_obs_windmill_secrets__SMTP_PORT: string;
		NOCODB_ADMIN_EMAIL: string;
		MOZ_X11_EGL: string;
		bc_obs_nocodb_secrets_powersheets__POSTGRES_PASSWORD: string;
		ICEAUTHORITY: string;
		vps_resend_secrets__cloudflare_zone_id: string;
		LANGUAGE: string;
		aa_sui_mattermost_mcp_secrets__MM_URL: string;
		OCI_USER_OCID: string;
		NODE: string;
		ab_mic_vaultwarden_secrets__SMTP_PASSWORD: string;
		ca_dat_backup_bup_secrets__PGPASSWORD: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_DB: string;
		bc_obs_matomo_secrets__MYSQL_ROOT_PASSWORD: string;
		LESS_TERMCAP_se: string;
		bc_obs_c3_services_mcp_secrets__DAGU_BASIC_AUTH: string;
		LESS_TERMCAP_so: string;
		ca_dat_backup_bup_secrets__SQLITE_DBS: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_SECRET: string;
		CLOUDFLARE_EMAIL: string;
		QT_LOGGING_RULES_DEFAULT_PRESENT: string;
		QT_LOGGING_RULES: string;
		ANTHROPIC_API_KEY: string;
		XDG_DATA_HOME: string;
		PROFILE: string;
		C3_API_KEY: string;
		MOZ_DRM_DEVICE: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SECRET: string;
		WG_GCP_PROXY_PRIVATE_KEY: string;
		bb_sec_caddy_secrets__AUTHELIA_CLI_SECRET: string;
		ac_fin_crawlee_cloud_secrets__RUNNER_TOKEN: string;
		aa_sui_photoprism_secrets__MARIADB_USER: string;
		SHELL_SESSION_ID: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUDFLARE_SECRET: string;
		XDG_CONFIG_HOME: string;
		aa_sui_mail_mcp_secrets__MAIL_PASSWORD: string;
		XCURSOR_PATH: string;
		MEMORY_PRESSURE_WRITE: string;
		bc_obs_windmill_secrets__DB_PASSWORD: string;
		bc_obs_c3_infra_mcp_secrets__C3_API_KEY: string;
		aa_sui_photoprism_secrets__MARIADB_PASSWORD: string;
		bc_obs_nocodb_secrets_powersheets__NC_AUTH_JWT_SECRET: string;
		COLOR: string;
		OPENAI_API_KEY: string;
		LOCALE_ARCHIVE_2_27: string;
		npm_config_local_prefix: string;
		WG_OCI_APPS_PRIVATE_KEY: string;
		LIBVA_DRIVER_NAME: string;
		GNUPGHOME: string;
		DESKTOP_SESSION: string;
		bb_sec_authelia_secrets__AUTHELIA_JWT_SECRET: string;
		LC_MONETARY: string;
		aa_sui_mattermost_bots_secrets__AUTHELIA_OIDC_MATTERMOST_SECRET: string;
		GDK_PIXBUF_MODULE_FILE: string;
		ca_dat_backup_bup_secrets__MYSQL_DBS: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_PASSWORD: string;
		ca_dat_db_agent_secrets__BUP_REMOTE: string;
		GTK_RC_FILES: string;
		npm_config_globalconfig: string;
		GPG_TTY: string;
		OCI_SSH_KEY: string;
		EDITOR: string;
		aa_sui_tools_stalwart_secrets__CF_DNS_API_TOKEN: string;
		ca_dat_db_agent_secrets__NTFY_TOPIC: string;
		FZF_ALT_C_OPTS: string;
		ab_mic_vaultwarden_secrets__SMTP_USERNAME: string;
		bc_obs_umami_secrets__DB_PASSWORD: string;
		XDG_SEAT: string;
		CARGO_TARGET_DIR: string;
		aa_sui_photoprism_secrets__OCI_S3_ACCESS_KEY: string;
		bc_obs_c3_infra_mcp_secrets__RESEND_API_KEY: string;
		OPENAI_BASE_URL: string;
		OCI_REGION: string;
		NAUTILUS_4_EXTENSION_DIR: string;
		PWD: string;
		XDG_VIDEOS_DIR: string;
		NIX_PROFILES: string;
		aa_sui_photoprism_secrets__OCI_S3_SECRET_KEY: string;
		NIX_GSETTINGS_OVERRIDES_DIR: string;
		LOGNAME: string;
		XDG_SESSION_DESKTOP: string;
		QT_QPA_PLATFORMTHEME: string;
		XDG_SESSION_TYPE: string;
		ca_dat_backup_bup_secrets__POSTGRES_DBS: string;
		TF_VAR_tenancy_ocid: string;
		ca_dat_kg_graph_secrets__SURREAL_ROOT_PASSWORD: string;
		WG_OCI_APPS_PUBLIC_KEY: string;
		NIX_PATH: string;
		home_manager__shared_secrets__GCP_COMPUTE_ENGINE: string;
		npm_config_init_module: string;
		SYSTEMD_EXEC_PID: string;
		NIXPKGS_CONFIG: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__MM_BOT_TOKEN: string;
		_: string;
		ca_dat_redis_secrets__REDIS_PASSWORD: string;
		aa_sui_mattermost_mcp_secrets__CLAUDE_MODEL: string;
		XAUTHORITY: string;
		ab_mic_vaultwarden_secrets__ADMIN_TOKEN: string;
		bc_obs_c3_infra_mcp_secrets__DAGU_PASSWORD: string;
		XDG_PICTURES_DIR: string;
		NoDefaultCurrentDirectoryInExePath: string;
		WG_OCI_ANALYTICS_PRIVATE_KEY: string;
		FZF_DEFAULT_COMMAND: string;
		MOZ_WEBRENDER: string;
		WG_TERMUX_PRIVATE_KEY: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_DB: string;
		TF_PLUGIN_CACHE_DIR: string;
		bc_obs_c3_infra_api_secrets__C3_API_KEY: string;
		bc_obs_c3_infra_mcp_secrets__MM_BOT_TOKEN: string;
		OCI_S3_ENDPOINT: string;
		ca_dat_backup_borg_secrets__SOURCE_DIRS: string;
		CLAUDECODE: string;
		ac_fin_crawlee_cloud_secrets__ADMIN_PASSWORD: string;
		OCI_TENANCY_OCID: string;
		AUTHELIA_JWKS_PUBLIC_KEY: string;
		aa_sui_mattermost_mcp_secrets__MM_TEAM_ID: string;
		WG_LOCAL_IP: string;
		XKB_DEFAULT_MODEL: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
		GTK2_RC_FILES: string;
		ab_mic_vaultwarden_secrets__SMTP_PORT: string;
		bc_obs_c3_infra_api_secrets__DAGU_USERNAME: string;
		NIXPKGS_QT6_QML_IMPORT_PATH: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NOCODB_SECRET: string;
		HOME: string;
		XDG_PUBLICSHARE_DIR: string;
		WG_OCI_MAIL_PUBLIC_KEY: string;
		SSH_ASKPASS: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SONNET_SECRET: string;
		LANG: string;
		bb_sec_caddy_secrets__NTFY_ADMIN_AUTH: string;
		TMUX_TMPDIR: string;
		GITHUB_TOKEN: string;
		aa_sui_tools_stalwart_secrets__AWS_RELAYPASSWORD: string;
		GCP_T4_SSH_KEY: string;
		FZF_CTRL_R_OPTS: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_C3_MCP_SECRET: string;
		XDG_CURRENT_DESKTOP: string;
		CARGO_HOME: string;
		KONSOLE_DBUS_SERVICE: string;
		npm_package_version: string;
		bc_obs_umami_secrets__ADMIN_USERNAME: string;
		ca_dat_backup_bup_secrets__PGUSER: string;
		OCI_S3_BUCKET: string;
		bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_PASSWORD: string;
		MEMORY_PRESSURE_WATCH: string;
		STARSHIP_SHELL: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_USER: string;
		OCI_S3_SECRET_KEY: string;
		bc_obs_nocodb_secrets_powersheets__NC_ADMIN_EMAIL: string;
		SSH_S21_ED25519_PUB: string;
		WAYLAND_DISPLAY: string;
		NOCODB_API_TOKEN: string;
		vps_resend_secrets__cloudflare_api_token: string;
		ba_clo_cloudflare_secrets__cloudflare_api_key: string;
		KONSOLE_DBUS_SESSION: string;
		PROFILEHOME: string;
		WG_HUB_IP: string;
		GIO_EXTRA_MODULES: string;
		bc_obs_windmill_secrets__SMTP_PASSWORD: string;
		XDG_DOWNLOAD_DIR: string;
		SOPS_AGE_KEY: string;
		WG_OCI_ANALYTICS_PUBLIC_KEY: string;
		HM_PROFILE: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_DB: string;
		aa_sui_mattermost_bots_secrets__MM_SQLSETTINGS_DATASOURCE: string;
		bc_obs_dagu_secrets__DAGU_USERNAME: string;
		XDG_SEAT_PATH: string;
		home_manager__shared_secrets__VAULT_ID_RSA: string;
		bc_obs_nocodb_secrets_powersheets__NC_ADMIN_PASSWORD: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_PASSWORD: string;
		aa_sui_tools_stalwart_secrets__ADMIN_PASSWORD: string;
		CF_API_KEY: string;
		XDG_MUSIC_DIR: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_EMAIL: string;
		NOCODB_URL: string;
		home_manager__shared_secrets__SURFACE_DEPLOY_PUB: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_HAIKU_SECRET: string;
		AUTHELIA_OIDC_CREDENTIALS_DIR: string;
		GCP_PROXY_SSH_KEY_PUB: string;
		XDG_TEMPLATES_DIR: string;
		aa_sui_tools_smtp_proxy_secrets__API_KEY: string;
		INVOCATION_ID: string;
		bc_obs_nocodb_secrets__POSTGRES_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_STORAGE_ENCRYPTION_KEY: string;
		ac_fin_crawlee_cloud_secrets__JWT_SECRET: string;
		KONSOLE_VERSION: string;
		aa_sui_tools_stalwart_secrets__AWS_RELAYUSER: string;
		vps_resend_secrets__resend_api_key: string;
		MANAGERPID: string;
		home_manager__shared_secrets__GCP_COMPUTE_ENGINE_PUB: string;
		PIP_CACHE_DIR: string;
		GCP_SERVICE_ACCOUNT_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_SECRET: string;
		home_manager__shared_secrets__ID_ED25519: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_USER: string;
		bc_obs_c3_infra_mcp_secrets__CF_API_EMAIL: string;
		GPG_PRIVATE_KEY: string;
		INIT_CWD: string;
		home_manager__shared_secrets__VAULT_ID_RSA_PUB: string;
		bc_obs_nocodb_secrets__NC_ADMIN_PASSWORD: string;
		bc_obs_windmill_secrets__OAUTH_CLIENT_SECRET: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_USERNAME: string;
		STARSHIP_SESSION_KEY: string;
		ac_fin_crawlee_cloud_secrets__MINIO_PASSWORD: string;
		bc_obs_matomo_secrets__MATOMO_DB_USER: string;
		KDE_SESSION_UID: string;
		MOZ_DISABLE_RDD_SANDBOX: string;
		WG_OCI_MAIL_PRIVATE_KEY: string;
		bc_obs_c3_services_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
		XDG_CACHE_HOME: string;
		home_manager__shared_secrets__SURFACE_NIXOS_PUB: string;
		NIX_USER_PROFILE_DIR: string;
		INFOPATH: string;
		npm_lifecycle_script: string;
		bc_obs_matomo_secrets__MATOMO_DB_PASSWORD: string;
		aa_sui_tools_stalwart_secrets__OCI_RELAYPASSWORD: string;
		ac_fin_crawlee_cloud_secrets__ADMIN_EMAIL: string;
		aa_sui_code_server_secrets__sudo_password: string;
		bc_obs_nocodb_secrets__NC_OIDC_CLIENT_SECRET: string;
		ab_mic_vaultwarden_secrets__SMTP_HOST: string;
		XKB_DEFAULT_LAYOUT: string;
		bc_obs_c3_infra_mcp_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_URL: string;
		OCI_API_KEY_PUB: string;
		npm_config_npm_version: string;
		ca_dat_backup_borg_secrets__BORG_PASSPHRASE: string;
		WG_GCP_PROXY_PUBLIC_KEY: string;
		XDG_SESSION_CLASS: string;
		XDG_DESKTOP_DIR: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_USER: string;
		GIT_BASE: string;
		CLOUDFLARE_API_KEY: string;
		PYTHONPATH: string;
		aa_sui_snappymail_secrets__SNAPPYMAIL_ADMIN_PASSWORD: string;
		TERM: string;
		ab_mic_vaultwarden_secrets__SMTP_SECURITY: string;
		npm_package_name: string;
		bc_obs_c3_infra_api_secrets__DAGU_PASSWORD: string;
		LESS_TERMCAP_mb: string;
		TF_VAR_compartment_ocid: string;
		FZF_CTRL_T_COMMAND: string;
		LESS_TERMCAP_me: string;
		GTK_PATH: string;
		LESS_TERMCAP_md: string;
		WG_INTERFACE: string;
		WG_SURFACE_PRIVATE_KEY: string;
		GPG_PUBLIC_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_SESSION_SECRET: string;
		SSH_SURFACE_PRO_ED25519_PUB: string;
		npm_config_prefix: string;
		bc_obs_umami_secrets__APP_SECRET: string;
		LESSOPEN: string;
		USER: string;
		ab_mic_vaultwarden_secrets__SMTP_FROM: string;
		bc_obs_c3_services_mcp_secrets__GITHUB_TOKEN: string;
		OCI_S3_ACCESS_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_USER_DIEGO_HASH: string;
		FZF_ALT_C_COMMAND: string;
		aa_sui_photoprism_secrets__MARIADB_ROOT_PASSWORD: string;
		WG_GHA_RUNNER_PUBLIC_KEY: string;
		COLORFGBG: string;
		ac_fin_crawlee_cloud_secrets__MINIO_USER: string;
		TZDIR: string;
		QT_WAYLAND_RECONNECT: string;
		FZF_CTRL_T_OPTS: string;
		aa_sui_tools_smtp_proxy_secrets__LISTEN_PORT: string;
		KDE_SESSION_VERSION: string;
		PAM_KWALLET5_LOGIN: string;
		CF_ZONE_ID: string;
		bc_obs_ntfy_secrets__NTFY_ADMIN_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_JWKS_KEY: string;
		ca_dat_backup_gitea_secrets__GITEA__security__INTERNAL_TOKEN: string;
		MANPAGER: string;
		VISUAL: string;
		bc_obs_c3_infra_api_secrets__MM_BOT_TOKEN: string;
		AUTHELIA_TOKEN_URL: string;
		DISPLAY: string;
		bb_sec_caddy_secrets__CF_API_TOKEN: string;
		npm_lifecycle_event: string;
		SHLVL: string;
		LESS_TERMCAP_ue: string;
		ca_dat_backup_borg_secrets__ARCHIVE_NAME: string;
		ca_dat_backup_gitea_secrets__GITEA__oauth2__JWT_SECRET: string;
		MOZ_ENABLE_WAYLAND: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_PASSWORD: string;
		SSH_SURFACE_PRO_ED25519: string;
		LESS_TERMCAP_us: string;
		GIT_EDITOR: string;
		ca_dat_backup_bup_secrets__PGHOST: string;
		__HM_ZSH_SESS_VARS_SOURCED: string;
		PAGER: string;
		WG_HUB_ENDPOINT: string;
		home_manager__shared_secrets__CLAUDE_WEBSERVER_PUB: string;
		ca_dat_db_agent_secrets__VM_NAME: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUD_ADMIN_SECRET: string;
		QTWEBKIT_PLUGIN_PATH: string;
		bc_obs_dagu_secrets__AUTHELIA_OIDC_DAGU_SECRET: string;
		TF_VAR_cloudflare_api_key: string;
		ca_dat_backup_gitea_secrets__GITEA__security__SECRET_KEY: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_PASSWORD: string;
		LC_MEASUREMENT: string;
		__NIXOS_SET_ENVIRONMENT_DONE: string;
		XDG_VTNR: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_CC_SECRET: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MONITORING_SECRET: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_ROOT_PASSWORD: string;
		NOCODB_XC_TOKEN: string;
		aa_sui_tools_smtp_proxy_secrets__SMTP_HOST: string;
		bc_obs_dagu_secrets__DAGU_PASSWORD: string;
		XDG_SESSION_ID: string;
		ca_dat_backup_bup_secrets__MYSQL_PASSWORD: string;
		LOCALE_ARCHIVE: string;
		bb_sec_authelia_secrets__AUTHELIA_REDIS_PASSWORD: string;
		SSH_S21_ED25519: string;
		ATUIN_SESSION: string;
		LESSKEYIN_SYSTEM: string;
		npm_config_user_agent: string;
		aa_sui_photoprism_secrets__PHOTOPRISM_ADMIN_PASSWORD: string;
		QML2_IMPORT_PATH: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_OPUS_SECRET: string;
		aa_sui_photoprism_secrets__MARIADB_DATABASE: string;
		TERMINFO_DIRS: string;
		DEVICE: string;
		aa_sui_code_server_secrets__CODE_SERVER_PASSWORD: string;
		WG_DNS: string;
		XDG_STATE_HOME: string;
		npm_execpath: string;
		home_manager__shared_secrets__MATOMO_SERVER_PUB: string;
		bc_obs_windmill_secrets__SMTP_HOST: string;
		bc_obs_c3_infra_api_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
		bc_obs_umami_secrets__ADMIN_PASSWORD: string;
		CF_API_EMAIL: string;
		ad_agi_rig_agentic_hai_1_5bq4_secrets__MM_BOT_TOKEN: string;
		aa_sui_tools_stalwart_secrets__NOREPLY_PASSWORD: string;
		aa_sui_tools_stalwart_secrets__ME_PASSWORD: string;
		bc_obs_c3_infra_mcp_secrets__CF_API_KEY: string;
		XDG_RUNTIME_DIR: string;
		bc_obs_windmill_secrets__OAUTH_CLIENT_ID: string;
		OCI_API_KEY: string;
		aa_sui_tools_stalwart_secrets__OCI_RELAYUSER: string;
		GCP_T4_SSH_KEY_PUB: string;
		GCP_PROXY_SSH_KEY: string;
		aa_sui_mattermost_bots_secrets__BEARER_TOKEN: string;
		NODE_PATH: string;
		CLAUDE_CODE_ENTRYPOINT: string;
		CF_DOMAIN: string;
		NIX_XDG_DESKTOP_PORTAL_DIR: string;
		AUTHELIA_OIDC_TOKENS_DIR: string;
		npm_package_json: string;
		LC_TIME: string;
		aa_sui_mail_mcp_secrets__RESEND_API_KEY: string;
		XDG_DOCUMENTS_DIR: string;
		bc_obs_nocodb_secrets__NC_AUTH_JWT_SECRET: string;
		bc_obs_c3_infra_mcp_secrets__DAGU_USERNAME: string;
		bc_obs_c3_infra_api_secrets__RESEND_API_KEY: string;
		bc_obs_dagu_secrets__BORG_PASSPHRASE: string;
		LC_ALL: string;
		OCI_SSH_KEY_PUB: string;
		WG_SURFACE_PUBLIC_KEY: string;
		QT_AUTO_SCREEN_SCALE_FACTOR: string;
		JOURNAL_STREAM: string;
		bc_obs_c3_infra_api_secrets__CF_API_EMAIL: string;
		XDG_DATA_DIRS: string;
		KDE_FULL_SESSION: string;
		LIBEXEC_PATH: string;
		CLAUDE_CODE_EXECPATH: string;
		SSH_S21_RSA: string;
		aa_sui_tools_smtp_proxy_secrets__SMTP_PORT: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NPM_SECRET: string;
		npm_config_noproxy: string;
		PATH: string;
		AUTHELIA_JWKS_PRIVATE_KEY: string;
		npm_config_node_gyp: string;
		__fish_nixos_env_preinit_sourced: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_URL: string;
		WGPU_BACKEND: string;
		DBUS_SESSION_BUS_ADDRESS: string;
		bb_sec_authelia_secrets__AUTHELIA_SMTP_PASSWORD: string;
		FZF_DEFAULT_OPTS: string;
		bc_obs_dagu_secrets__RESTIC_PASSWORD: string;
		npm_config_global_prefix: string;
		KDE_APPLICATIONS_AS_SCOPE: string;
		bc_obs_matomo_secrets__MATOMO_DB_NAME: string;
		KPACKAGE_DEP_RESOLVERS_PATH: string;
		aa_sui_mattermost_bots_secrets__POSTGRES_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLI_SECRET: string;
		QT_PLUGIN_PATH: string;
		OCI_FINGERPRINT: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_USER: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_HMAC_SECRET: string;
		TF_VAR_region: string;
		aa_sui_mail_mcp_secrets__MAIL_USER: string;
		VAULT_DEPLOY_KEY: string;
		XKB_DEFAULT_OPTIONS: string;
		npm_node_execpath: string;
		WG_TERMUX_PUBLIC_KEY: string;
		bc_obs_windmill_secrets__SMTP_FROM: string;
		bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_USER: string;
		LC_NUMERIC: string;
		OLDPWD: string;
		GOPATH: string;
		KONSOLE_DBUS_WINDOW: string;
		CF_API_TOKEN: string;
		NODE_ENV: string;
		[key: `PUBLIC_${string}`]: undefined;
		[key: `${string}`]: string | undefined;
	}
}

/**
 * Similar to [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), but only includes variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Note that public dynamic environment variables must all be sent from the server to the client, causing larger network requests — when possible, use `$env/static/public` instead.
 * 
 * ```ts
 * import { env } from '$env/dynamic/public';
 * console.log(env.PUBLIC_DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 */
declare module '$env/dynamic/public' {
	export const env: {
		[key: `PUBLIC_${string}`]: string | undefined;
	}
}
