// Fully data-driven Food Tables page.
// All UI rows, presets, columns, filters and computed ratios come from
// PORTAL_DATA["food-library"] which is generated by src/data/build-food-library.ts.

import type { ColumnDef, FilterTag, FoodItem, FoodLibrary, Preset, UiRow } from "./types";

const ROW_ORDER = ["diet", "diet-protein", "diet-carb", "restrictions", "customs"] as const;
const PARENT_ROW = "diet";
const CUSTOM_TAG: FilterTag = "custom";
const ALL_TAG: FilterTag = "all";
const PAGE_SIZE = 20;

interface SortState { key: string; dir: "asc" | "desc"; }
interface TableViewState { page: number; query: string; }

const state: {
  lib: FoodLibrary | null;
  active: Map<string, Set<FilterTag>>;
  protSort: SortState;
  carbSort: SortState;
  customSort: SortState;
  protView: TableViewState;
  carbView: TableViewState;
  customView: TableViewState;
} = {
  lib: null,
  active: new Map(),
  protSort:   { key: "kcal_per_prot", dir: "asc" },
  carbSort:   { key: "gi",            dir: "asc" },
  customSort: { key: "umami_score",   dir: "desc" },
  protView:   { page: 1, query: "" },
  carbView:   { page: 1, query: "" },
  customView: { page: 1, query: "" },
};

function getLibrary(): FoodLibrary | null {
  const raw = window.PORTAL_DATA?.["food-library"] as FoodLibrary | undefined;
  return raw && Array.isArray(raw.items) ? raw : null;
}

function rows(): Array<[string, UiRow]> {
  if (!state.lib) return [];
  return ROW_ORDER
    .filter(id => state.lib!.ui_rows[id])
    .map(id => [id, state.lib!.ui_rows[id]] as [string, UiRow]);
}

type TableSlot = "protein" | "carb" | "custom";

function viewOf(slot: TableSlot): TableViewState {
  return slot === "protein" ? state.protView : slot === "carb" ? state.carbView : state.customView;
}
function sortOf(slot: TableSlot): SortState {
  return slot === "protein" ? state.protSort : slot === "carb" ? state.carbSort : state.customSort;
}

function activeCustomKey(): string | null {
  // Returns the active custom view key (e.g. "umami") or null when "all" / nothing.
  const sel = state.active.get("customs");
  if (!sel) return null;
  for (const t of sel) if (t !== ALL_TAG && t !== CUSTOM_TAG) return t;
  return null;
}

function tableColumnsKey(slot: TableSlot): string {
  if (slot === "custom") {
    const ck = activeCustomKey();
    return ck ? `custom-${ck}` : "";
  }
  return slot;
}

function defaultDir(slot: TableSlot, key: string): "asc" | "desc" {
  const colsKey = tableColumnsKey(slot);
  const col = (state.lib?.table_columns[colsKey] ?? []).find(c => c.key === key);
  return col?.default_dir ?? "asc";
}

// ─── Filter logic ─────────────────────────────────────────────────────────────
function passesFilters(item: FoodItem): boolean {
  if (!state.lib) return true;
  // For each row: if row's selection contains "all" or "custom", that row contributes nothing.
  // Otherwise every selected tag in that row must appear in item.diet_tags.
  // Parent "diet" row contributes nothing — it's a preset trigger only; children carry the actual constraints.
  for (const [rowId] of rows()) {
    if (rowId === PARENT_ROW) continue;
    const sel = state.active.get(rowId);
    if (!sel || sel.has(ALL_TAG) || sel.size === 0) continue;
    const tags = [...sel].filter(t => t !== ALL_TAG && t !== CUSTOM_TAG);
    if (tags.length === 0) continue;
    if (!tags.every(tag => item.diet_tags.includes(tag))) return false;
  }
  return true;
}

// ─── Preset wiring ────────────────────────────────────────────────────────────
function applyPreset(presetKey: string): void {
  if (!state.lib) return;
  if (presetKey === ALL_TAG || presetKey === CUSTOM_TAG) {
    // Reset every child row to "all"
    for (const [rowId] of rows()) {
      if (rowId === PARENT_ROW) continue;
      state.active.set(rowId, new Set([ALL_TAG]));
    }
    state.active.set(PARENT_ROW, new Set([presetKey]));
    return;
  }
  const preset = state.lib.presets[presetKey] as Preset | undefined;
  if (!preset) return;
  state.active.set("diet-protein", new Set([preset.protein || ALL_TAG]));
  state.active.set("diet-carb",    new Set([preset.carb    || ALL_TAG]));
  const restr = preset.restrictions && preset.restrictions.length > 0
    ? new Set<FilterTag>(preset.restrictions)
    : new Set<FilterTag>([ALL_TAG]);
  state.active.set("restrictions", restr);
  state.active.set(PARENT_ROW,     new Set([presetKey]));
}

function detectActivePreset(): string | null {
  // Returns the preset key whose child-row config matches the current state, or null.
  if (!state.lib) return null;
  for (const [pkey, presetRaw] of Object.entries(state.lib.presets)) {
    if (pkey.startsWith("_")) continue;
    const preset = presetRaw as Preset;
    const protSel = state.active.get("diet-protein");
    const carbSel = state.active.get("diet-carb");
    const restrSel = state.active.get("restrictions");
    const protOk = protSel && protSel.size === 1 && protSel.has(preset.protein || ALL_TAG);
    const carbOk = carbSel && carbSel.size === 1 && carbSel.has(preset.carb    || ALL_TAG);
    const wantRestr = preset.restrictions && preset.restrictions.length > 0
      ? new Set<FilterTag>(preset.restrictions)
      : new Set<FilterTag>([ALL_TAG]);
    const restrOk = restrSel && restrSel.size === wantRestr.size && [...wantRestr].every(t => restrSel.has(t));
    if (protOk && carbOk && restrOk) return pkey;
  }
  // Check "all" state
  const allChildren = ROW_ORDER.filter(r => r !== PARENT_ROW).every(r => {
    const s = state.active.get(r);
    return s && s.size === 1 && s.has(ALL_TAG);
  });
  if (allChildren) return ALL_TAG;
  return null;
}

function refreshParentChip(): void {
  const detected = detectActivePreset();
  state.active.set(PARENT_ROW, new Set([detected ?? CUSTOM_TAG]));
}

// ─── Toggle ───────────────────────────────────────────────────────────────────
function toggleFilter(rowId: string, tag: FilterTag): void {
  if (!state.lib) return;
  if (rowId === PARENT_ROW) {
    applyPreset(tag);
    return;
  }
  const row = state.lib.ui_rows[rowId];
  const sel = state.active.get(rowId);
  if (!row || !sel) return;
  if (row.selectMode === "single") {
    sel.clear();
    sel.add(tag);
  } else {
    if (tag === ALL_TAG) {
      sel.clear();
      sel.add(ALL_TAG);
    } else {
      sel.delete(ALL_TAG);
      if (sel.has(tag)) sel.delete(tag);
      else sel.add(tag);
      if (sel.size === 0) sel.add(ALL_TAG);
    }
  }
  refreshParentChip();
}

// ─── Render ───────────────────────────────────────────────────────────────────
function fmt(v: unknown, decimals = 2): string {
  if (typeof v !== "number" || !Number.isFinite(v)) return "—";
  return v.toFixed(decimals).replace(/\.?0+$/, "") || "0";
}

function chipLabel(rowId: string, tag: FilterTag): string {
  if (!state.lib) return tag;
  if (tag === ALL_TAG)    return "All";
  if (tag === CUSTOM_TAG) return "Custom";
  if (rowId === PARENT_ROW) return state.lib.presets[tag]?.label ?? tag;
  // Capitalize for sub-row chips (vegan -> Vegan, lactose-free -> Lac-free etc.)
  const aliases: Record<string, string> = { "lactose-free": "Lac-free", "gluten-free": "Gluten-free", "low-ldl": "Low-LDL", "low-carb": "Low-Carb", "low-sodium": "Low-Sodium", "low-fodmap": "Low-FODMAP", "no-legumes": "No-Legumes", "no-grains": "No-Grains", "no-refined-sugar": "No-Refined-Sugar", "no-sugar": "No-Sugar" };
  return aliases[tag] ?? (tag.charAt(0).toUpperCase() + tag.slice(1));
}

function renderFilters(): string {
  return rows().map(([rowId, row]) => {
    const isParent = rowId === PARENT_ROW;
    const sel = state.active.get(rowId) ?? new Set([ALL_TAG]);
    const opts = isParent
      ? [...row.options]
      : [...row.options];
    const chips = opts.map(tag => `
      <button type="button" class="ft-chip ${sel.has(tag) ? "is-active" : ""}" data-row="${rowId}" data-tag="${tag}">${chipLabel(rowId, tag)}</button>
    `).join("");
    const indentClass = isParent ? "ft-row-parent" : "ft-row-child";
    return `
      <div class="ft-row ${indentClass}" data-row="${rowId}">
        <span class="ft-row-label">${row.label}</span>
        <div class="ft-row-chips">${chips}</div>
      </div>
    `;
  }).join("");
}

function sortRows(items: FoodItem[], cols: ColumnDef[], sort: SortState): FoodItem[] {
  const dir = sort.dir === "asc" ? 1 : -1;
  return items.slice().sort((a, b) => {
    const va = (a as any)[sort.key];
    const vb = (b as any)[sort.key];
    if (sort.key === "name") {
      const sa = String(va ?? "").toLowerCase();
      const sb = String(vb ?? "").toLowerCase();
      if (sa < sb) return -1 * dir;
      if (sa > sb) return  1 * dir;
      return 0;
    }
    const na = typeof va === "number" && Number.isFinite(va) ? va : (sort.dir === "asc" ?  Infinity : -Infinity);
    const nb = typeof vb === "number" && Number.isFinite(vb) ? vb : (sort.dir === "asc" ?  Infinity : -Infinity);
    if (na < nb) return -1 * dir;
    if (na > nb) return  1 * dir;
    return 0;
  });
}

function renderHead(cols: ColumnDef[], sort: SortState): string {
  const cells = cols.map(c => {
    const isActive = c.key === sort.key;
    const arrow = isActive ? (sort.dir === "asc" ? "▲" : "▼") : "";
    const cls = ["th-sort", c.align === "left" ? "th-left" : "th-right", isActive ? "th-active" : ""].filter(Boolean).join(" ");
    return `<th class="${cls}" data-key="${c.key}" tabindex="0" role="button" aria-sort="${isActive ? (sort.dir === "asc" ? "ascending" : "descending") : "none"}">
      <span class="th-label">${c.label}</span><span class="th-arrow">${arrow}</span>
    </th>`;
  }).join("");
  return `<tr><th class="rank">#</th>${cells}</tr>`;
}

function cellValue(rec: FoodItem, col: ColumnDef): string {
  if (col.key === "name") return String(rec.name);
  const v = (rec as any)[col.key];
  if (typeof v !== "number" || !Number.isFinite(v)) return "—";
  // Use the ratio's `decimals` if available, else 2
  const ratios = state.lib?.computed_ratios ?? {};
  const dec = ratios[col.key]?.decimals ?? (col.key === "kcal_per_100g" ? 0 : col.key === "gi" ? 0 : 2);
  return fmt(v, dec);
}

function renderBody(items: FoodItem[], cols: ColumnDef[]): string {
  if (items.length === 0) return `<tr><td colspan="${cols.length + 1}" class="empty">No foods match these filters.</td></tr>`;
  return items.map((r, i) => {
    const cells = cols.map(c => {
      const cls = [c.align === "left" ? "name" : "metric", c.tone ?? "", c.primary ? "primary" : ""].filter(Boolean).join(" ");
      return `<td class="${cls}">${cellValue(r, c)}</td>`;
    }).join("");
    return `<tr><td class="rank">${i + 1}</td>${cells}</tr>`;
  }).join("");
}

function applyTableFilter(items: FoodItem[], filter: { min?: Record<string,number>; max?: Record<string,number>; require?: string[]; } | undefined): FoodItem[] {
  if (!filter) return items;
  return items.filter(it => {
    if (filter.min) for (const [k,v] of Object.entries(filter.min)) {
      const x = (it as any)[k];
      if (typeof x !== "number" || x < v) return false;
    }
    if (filter.max) for (const [k,v] of Object.entries(filter.max)) {
      const x = (it as any)[k];
      if (typeof x !== "number" || x > v) return false;
    }
    if (filter.require) for (const k of filter.require) {
      const x = (it as any)[k];
      if (x == null) return false;
    }
    return true;
  });
}

function renderPager(slot: TableSlot, total: number, page: number, totalPages: number): string {
  const prevDisabled = page <= 1;
  const nextDisabled = page >= totalPages;
  const start = total === 0 ? 0 : (page - 1) * PAGE_SIZE + 1;
  const end = Math.min(page * PAGE_SIZE, total);
  return `
    <div class="ft-pager" data-slot="${slot}">
      <button type="button" class="ft-pager-btn" data-page="prev" ${prevDisabled ? "disabled" : ""}>← Prev</button>
      <span class="ft-pager-info">${start}–${end} of ${total} (page ${page} / ${totalPages || 1})</span>
      <button type="button" class="ft-pager-btn" data-page="next" ${nextDisabled ? "disabled" : ""}>Next →</button>
    </div>
  `;
}

function renderTable(slot: TableSlot): string {
  if (!state.lib) return "";
  const colsKey = tableColumnsKey(slot);
  // Custom table is hidden when no specific custom view is active
  if (slot === "custom" && !colsKey) {
    return `<div class="ft-table-head"><h2>Custom View</h2><p class="ft-subtitle">Pick a chip in <strong>Customs</strong> above (e.g. <em>Umami</em>) to populate this table.</p></div>`;
  }
  const cols = state.lib.table_columns[colsKey] ?? [];
  const filter = state.lib.table_filters[colsKey];
  const view = viewOf(slot);
  const sortRef = sortOf(slot);

  let filtered = applyTableFilter(state.lib.items, filter).filter(passesFilters);
  if (view.query.trim()) {
    const q = view.query.trim().toLowerCase();
    filtered = filtered.filter(it => it.name.toLowerCase().includes(q));
  }
  const sorted = sortRows(filtered, cols, sortRef);

  const total = sorted.length;
  const totalPages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  if (view.page > totalPages) view.page = totalPages;
  if (view.page < 1) view.page = 1;
  const pageStart = (view.page - 1) * PAGE_SIZE;
  const pageItems = sorted.slice(pageStart, pageStart + PAGE_SIZE);
  // Re-rank labels are 1..PAGE_SIZE per page; show absolute rank instead
  const indexedItems = pageItems.map((it, i) => ({ ...it, _rank: pageStart + i + 1 }));

  const ck = activeCustomKey();
  const subtitle = slot === "protein"
    ? "Click any column to sort. Default: lowest kcal per gram of protein (leanest first)."
    : slot === "carb"
      ? "Click any column to sort. Default: lowest Glycemic Index (slowest blood-sugar rise)."
      : ck === "umami"
        ? "Click any column to sort. Ranked by umami score (free glutamate + 5×(IMP+GMP) + synergy bonus)."
        : "";
  const heading = slot === "protein"
    ? "Protein Sources"
    : slot === "carb"
      ? "Carbohydrate Sources"
      : ck === "umami"
        ? "Umami Foods"
        : "Custom View";
  return `
    <div class="ft-table-head">
      <h2>${heading}</h2>
      <span class="ft-count">${total} item${total === 1 ? "" : "s"}</span>
      <p class="ft-subtitle">${subtitle}</p>
      <div class="ft-table-toolbar">
        <input type="search" class="ft-search" data-slot="${slot}" placeholder="Search by name…" value="${escapeAttr(view.query)}" />
      </div>
    </div>
    <div class="ft-table-wrap">
      <table class="ft-table">
        <thead>${renderHead(cols, sortRef)}</thead>
        <tbody>${renderBodyRanked(indexedItems, cols)}</tbody>
      </table>
    </div>
    ${renderPager(slot, total, view.page, totalPages)}
  `;
}

function renderBodyRanked(items: Array<FoodItem & { _rank: number }>, cols: ColumnDef[]): string {
  if (items.length === 0) return `<tr><td colspan="${cols.length + 1}" class="empty">No foods match these filters.</td></tr>`;
  return items.map(r => {
    const cells = cols.map(c => {
      const cls = [c.align === "left" ? "name" : "metric", c.tone ?? "", c.primary ? "primary" : ""].filter(Boolean).join(" ");
      return `<td class="${cls}">${cellValue(r, c)}</td>`;
    }).join("");
    return `<tr><td class="rank">${r._rank}</td>${cells}</tr>`;
  }).join("");
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function rerenderTables(): void {
  const protSlot = document.getElementById("ft-protein");
  const carbSlot = document.getElementById("ft-carb");
  const customSlot = document.getElementById("ft-custom");
  if (protSlot)   protSlot.innerHTML   = renderTable("protein");
  if (carbSlot)   carbSlot.innerHTML   = renderTable("carb");
  if (customSlot) customSlot.innerHTML = renderTable("custom");
}

function rerenderFilters(): void {
  const slot = document.getElementById("ft-filters");
  if (slot) slot.innerHTML = renderFilters();
}

function bindFilterClicks(): void {
  const slot = document.getElementById("ft-filters");
  if (!slot) return;
  slot.addEventListener("click", (ev) => {
    const target = ev.target as HTMLElement | null;
    const chip = target?.closest<HTMLButtonElement>(".ft-chip");
    if (!chip) return;
    const rowId = chip.dataset.row;
    const tag = chip.dataset.tag as FilterTag | undefined;
    if (!rowId || !tag) return;
    toggleFilter(rowId, tag);
    // Reset all tables to page 1 since filter set changed
    state.protView.page = 1;
    state.carbView.page = 1;
    state.customView.page = 1;
    rerenderFilters();
    rerenderTables();
  });
}

function bindTableEvents(slotId: string, slot: TableSlot): void {
  const el = document.getElementById(slotId);
  if (!el) return;

  // Sort header click (delegated)
  el.addEventListener("click", (ev) => {
    const target = ev.target as HTMLElement | null;
    const th = target?.closest<HTMLElement>(".th-sort");
    if (th) {
      const key = th.dataset.key;
      if (!key) return;
      const sortRef = sortOf(slot);
      if (sortRef.key === key) {
        sortRef.dir = sortRef.dir === "asc" ? "desc" : "asc";
      } else {
        sortRef.key = key;
        sortRef.dir = defaultDir(slot, key);
      }
      // Reset to page 1 on sort change
      const view = viewOf(slot);
      view.page = 1;
      rerenderTables();
      return;
    }
    // Pager buttons
    const pageBtn = target?.closest<HTMLButtonElement>(".ft-pager-btn");
    if (pageBtn && !pageBtn.disabled) {
      const view = viewOf(slot);
      if (pageBtn.dataset.page === "prev") view.page = Math.max(1, view.page - 1);
      if (pageBtn.dataset.page === "next") view.page = view.page + 1;
      rerenderTables();
      return;
    }
  });

  // Sort header keyboard
  el.addEventListener("keydown", (ev) => {
    const ke = ev as KeyboardEvent;
    if (ke.key === "Enter" || ke.key === " ") {
      const t = ke.target as HTMLElement | null;
      const th = t?.closest<HTMLElement>(".th-sort");
      if (!th) return;
      ke.preventDefault();
      const key = th.dataset.key;
      if (!key) return;
      const sortRef = sortOf(slot);
      if (sortRef.key === key) sortRef.dir = sortRef.dir === "asc" ? "desc" : "asc";
      else { sortRef.key = key; sortRef.dir = defaultDir(slot, key); }
      const view = viewOf(slot);
      view.page = 1;
      rerenderTables();
    }
  });

  // Search input (delegated; preserves focus across re-renders)
  el.addEventListener("input", (ev) => {
    const target = ev.target as HTMLInputElement | null;
    if (!target?.classList.contains("ft-search")) return;
    const view = viewOf(slot);
    view.query = target.value;
    view.page = 1;
    const slotEl = document.getElementById(slotId);
    if (slotEl) {
      slotEl.innerHTML = renderTable(slot);
      const newInput = slotEl.querySelector<HTMLInputElement>(".ft-search");
      if (newInput) {
        newInput.focus();
        newInput.setSelectionRange(newInput.value.length, newInput.value.length);
      }
    }
  });
}

function init(): void {
  const lib = getLibrary();
  if (!lib) {
    const root = document.getElementById("ft-root");
    if (root) root.innerHTML = `<p class="ft-error">Food library unavailable. Reload the page.</p>`;
    return;
  }
  state.lib = lib;
  // Initialise every row to "all" then mark parent as "all"
  for (const [rowId] of rows()) state.active.set(rowId, new Set([ALL_TAG]));

  rerenderFilters();
  rerenderTables();
  bindFilterClicks();
  bindTableEvents("ft-protein", "protein");
  bindTableEvents("ft-carb",    "carb");
  bindTableEvents("ft-custom",  "custom");
}

if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", init);
} else {
  init();
}
