// All shapes mirror food-library.json (generated by src/data/build-food-library.ts).

export type FilterTag = string; // diet/restriction/preset tag — validated against ui_rows at runtime

export interface FoodItem {
  id: string;
  name: string;
  source: string;
  category: string | null;
  kcal_per_100g: number | null;
  prot_g: number | null;
  carb_g: number | null;
  fiber_g: number | null;
  sugar_g: number | null;
  fat_g: number | null;
  fat_sat_g: number | null;
  fat_mono_g: number | null;
  fat_poly_g: number | null;
  sodium_mg: number | null;
  gi: number | null;
  diet_tags: string[];
  // Precomputed ratios (defined in food-table-inputs.json → computed_ratios)
  kcal_per_prot?: number | null;
  prot_per_kcal?: number | null;
  prot_per_carb?: number | null;
  fat_good_g?: number | null;
  fat_bad_g?: number | null;
  net_carb_g?: number | null;
  glycemic_load?: number | null;
  kcal_per_g?: number | null;
  [extra: string]: unknown;
}

export interface Preset {
  label: string;
  protein: string;
  carb: string;
  restrictions: string[];
}

export interface UiRow {
  label: string;
  selectMode: "single" | "multi";
  options: string[];
}

export interface ColumnDef {
  key: string;
  label: string;
  align: "left" | "right";
  sortable: boolean;
  default_dir: "asc" | "desc";
  primary?: boolean;
  tone?: "good" | "bad";
}

export interface TableFilter {
  min?: Record<string, number>;
  max?: Record<string, number>;
  require?: string[];
}

export interface FoodLibrary {
  _meta: { generated_at: string; sources: string[]; total_foods: number; with_gi: number; with_fiber: number; with_fat_breakdown: number; };
  presets: Record<string, Preset & { _doc?: string }>;
  ui_rows: Record<string, UiRow & { _doc?: string }>;
  computed_ratios: Record<string, { formula: string; default_dir: "asc"|"desc"; decimals: number; _doc?: string }>;
  table_columns: Record<string, ColumnDef[]>;
  table_filters: Record<string, TableFilter>;
  items: FoodItem[];
}

declare global {
  interface Window {
    PORTAL_DATA: Record<string, unknown>;
  }
}
