
// this file is generated — do not edit it


/// <reference types="@sveltejs/kit" />

/**
 * Environment variables [loaded by Vite](https://vitejs.dev/guide/env-and-mode.html#env-files) from `.env` files and `process.env`. Like [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), this module cannot be imported into client-side code. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * _Unlike_ [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), the values exported from this module are statically injected into your bundle at build time, enabling optimisations like dead code elimination.
 * 
 * ```ts
 * import { API_KEY } from '$env/static/private';
 * ```
 * 
 * Note that all environment variables referenced in your code should be declared (for example in an `.env` file), even if they don't have a value until the app is deployed:
 * 
 * ```
 * MY_FEATURE_FLAG=""
 * ```
 * 
 * You can override `.env` values from the command line like so:
 * 
 * ```sh
 * MY_FEATURE_FLAG="enabled" npm run dev
 * ```
 */
declare module '$env/static/private' {
	export const SHELL: string;
	export const npm_command: string;
	export const aa_sui_radicale_secrets__RADICALE_USERS: string;
	export const bc_obs_ntfy_secrets__NTFY_USER_PASSWORD: string;
	export const SSH_S21_RSA_PUB: string;
	export const bc_obs_c3_infra_api_secrets__CF_API_KEY: string;
	export const ca_dat_db_agent_secrets__NTFY_URL: string;
	export const npm_config_userconfig: string;
	export const bc_obs_nocodb_secrets__NC_ADMIN_EMAIL: string;
	export const COLORTERM: string;
	export const VAULT_DEPLOY_KEY_FILE: string;
	export const __HM_SESS_VARS_SOURCED: string;
	export const bc_obs_dagu_secrets__OCI_S3_SECRET_KEY: string;
	export const aa_sui_tools_stalwart_secrets__DKIM_PRIVATE_KEY_B64: string;
	export const SSH_S21_RSA_FILE: string;
	export const aa_sui_mattermost_bots_secrets__MM_CLAUDE_PASSWORD: string;
	export const RESEND_API_KEY: string;
	export const npm_config_cache: string;
	export const aa_sui_mattermost_mcp_secrets__MM_ADMIN_USERNAME: string;
	export const LESS: string;
	export const CRAWLEE_API_TOKEN: string;
	export const ca_dat_backup_bup_secrets__MYSQL_USER: string;
	export const DTK_NODE_NAME: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_CC_SECRET: string;
	export const AUTHELIA_OIDC_CLIENT_ID: string;
	export const aa_sui_google_workspace_mcp_secrets__GOOGLE_SERVICE_ACCOUNT_KEY: string;
	export const WIREGUARD_PUBLIC_IP: string;
	export const TERMUX_APP__USER_ID: string;
	export const WG_PRIVATE_KEY: string;
	export const ca_dat_backup_bup_secrets__MYSQL_HOST: string;
	export const aa_sui_mattermost_mcp_secrets__MM_CLAUDE_PASSWORD: string;
	export const OCI_S3_REGION: string;
	export const bc_obs_windmill_secrets__SMTP_USERNAME: string;
	export const bc_obs_windmill_secrets__SMTP_PORT: string;
	export const NOCODB_ADMIN_EMAIL: string;
	export const bc_obs_nocodb_secrets_powersheets__POSTGRES_PASSWORD: string;
	export const vps_resend_secrets__cloudflare_zone_id: string;
	export const AUTHELIA_JWKS_PUBLIC_KEY_FILE: string;
	export const PREFIX: string;
	export const aa_sui_mattermost_mcp_secrets__MM_URL: string;
	export const OCI_USER_OCID: string;
	export const NODE: string;
	export const ab_mic_vaultwarden_secrets__SMTP_PASSWORD: string;
	export const ca_dat_backup_bup_secrets__PGPASSWORD: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_DB: string;
	export const bc_obs_matomo_secrets__MYSQL_ROOT_PASSWORD: string;
	export const TERMUX_APP__UID: string;
	export const bc_obs_c3_services_mcp_secrets__DAGU_BASIC_AUTH: string;
	export const ca_dat_backup_bup_secrets__SQLITE_DBS: string;
	export const OCI_API_KEY_FILE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_SECRET: string;
	export const CLOUDFLARE_EMAIL: string;
	export const ANTHROPIC_API_KEY: string;
	export const SHELL_CMD__RUNNER_NAME: string;
	export const MALLOC_ARENA_MAX: string;
	export const TERMUX_APP__PACKAGE_NAME: string;
	export const C3_API_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SECRET: string;
	export const WG_GCP_PROXY_PRIVATE_KEY: string;
	export const bb_sec_caddy_secrets__AUTHELIA_CLI_SECRET: string;
	export const aa_sui_photoprism_secrets__MARIADB_USER: string;
	export const ac_fin_crawlee_cloud_secrets__RUNNER_TOKEN: string;
	export const GCP_PROXY_SSH_KEY_FILE: string;
	export const aa_sui_mail_mcp_secrets__MAIL_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUDFLARE_SECRET: string;
	export const bc_obs_windmill_secrets__DB_PASSWORD: string;
	export const aa_sui_photoprism_secrets__MARIADB_PASSWORD: string;
	export const bc_obs_c3_infra_mcp_secrets__C3_API_KEY: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_AUTH_JWT_SECRET: string;
	export const TERMUX_APP__SE_PROCESS_CONTEXT: string;
	export const TERMUX_APP__VERSION_NAME: string;
	export const COLOR: string;
	export const OPENAI_API_KEY: string;
	export const TERMUX_APP__APK_PATH: string;
	export const LOCALE_ARCHIVE_2_27: string;
	export const npm_config_local_prefix: string;
	export const WG_OCI_APPS_PRIVATE_KEY: string;
	export const AUTHELIA_JWKS_PRIVATE_KEY_FILE: string;
	export const GPG_PUBLIC_KEY_FILE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_JWT_SECRET: string;
	export const aa_sui_mattermost_bots_secrets__AUTHELIA_OIDC_MATTERMOST_SECRET: string;
	export const ca_dat_backup_bup_secrets__MYSQL_DBS: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_PASSWORD: string;
	export const ca_dat_db_agent_secrets__BUP_REMOTE: string;
	export const npm_config_globalconfig: string;
	export const TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE: string;
	export const EDITOR: string;
	export const aa_sui_tools_stalwart_secrets__CF_DNS_API_TOKEN: string;
	export const ca_dat_db_agent_secrets__NTFY_TOPIC: string;
	export const TERMUX_APP__PACKAGE_VARIANT: string;
	export const ab_mic_vaultwarden_secrets__SMTP_USERNAME: string;
	export const bc_obs_umami_secrets__DB_PASSWORD: string;
	export const aa_sui_photoprism_secrets__OCI_S3_ACCESS_KEY: string;
	export const bc_obs_c3_infra_mcp_secrets__RESEND_API_KEY: string;
	export const OCI_REGION: string;
	export const OPENAI_BASE_URL: string;
	export const PWD: string;
	export const NIX_PROFILES: string;
	export const aa_sui_photoprism_secrets__OCI_S3_SECRET_KEY: string;
	export const PROOT_TMP_DIR: string;
	export const WIREGUARD_IP: string;
	export const ca_dat_backup_bup_secrets__POSTGRES_DBS: string;
	export const TF_VAR_tenancy_ocid: string;
	export const WG_OCI_APPS_PUBLIC_KEY: string;
	export const ca_dat_kg_graph_secrets__SURREAL_ROOT_PASSWORD: string;
	export const NIX_PATH: string;
	export const home_manager__shared_secrets__GCP_COMPUTE_ENGINE: string;
	export const npm_config_init_module: string;
	export const TERMUX_APP__FILES_DIR: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__MM_BOT_TOKEN: string;
	export const GCP_SERVICE_ACCOUNT_KEY_FILE: string;
	export const _: string;
	export const ca_dat_redis_secrets__REDIS_PASSWORD: string;
	export const aa_sui_mattermost_mcp_secrets__CLAUDE_MODEL: string;
	export const ab_mic_vaultwarden_secrets__ADMIN_TOKEN: string;
	export const GPG_PRIVATE_KEY_FILE: string;
	export const bc_obs_c3_infra_mcp_secrets__DAGU_PASSWORD: string;
	export const WG_OCI_ANALYTICS_PRIVATE_KEY: string;
	export const TERMUX_VERSION: string;
	export const WG_TERMUX_PRIVATE_KEY: string;
	export const TF_PLUGIN_CACHE_DIR: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_DB: string;
	export const bc_obs_c3_infra_api_secrets__C3_API_KEY: string;
	export const bc_obs_c3_infra_mcp_secrets__MM_BOT_TOKEN: string;
	export const OCI_S3_ENDPOINT: string;
	export const ca_dat_backup_borg_secrets__SOURCE_DIRS: string;
	export const TERMUX_APP__SE_INFO: string;
	export const ac_fin_crawlee_cloud_secrets__ADMIN_PASSWORD: string;
	export const OCI_TENANCY_OCID: string;
	export const aa_sui_mattermost_mcp_secrets__MM_TEAM_ID: string;
	export const SYSTEMSERVERCLASSPATH: string;
	export const EXTERNAL_STORAGE: string;
	export const LD_PRELOAD: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
	export const ab_mic_vaultwarden_secrets__SMTP_PORT: string;
	export const bc_obs_c3_infra_api_secrets__DAGU_USERNAME: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NOCODB_SECRET: string;
	export const HOME: string;
	export const WG_OCI_MAIL_PUBLIC_KEY: string;
	export const GCP_T4_SSH_KEY_FILE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SONNET_SECRET: string;
	export const LANG: string;
	export const bb_sec_caddy_secrets__NTFY_ADMIN_AUTH: string;
	export const SHELL_CMD__TERMINAL_SESSION_NUMBER_SINCE_BOOT: string;
	export const TERMUX_APP__PID: string;
	export const GITHUB_TOKEN: string;
	export const TMUX_TMPDIR: string;
	export const aa_sui_tools_stalwart_secrets__AWS_RELAYPASSWORD: string;
	export const TERMUX_APP__PACKAGE_MANAGER: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_C3_MCP_SECRET: string;
	export const GC_NPROCS: string;
	export const bc_obs_umami_secrets__ADMIN_USERNAME: string;
	export const OCI_S3_BUCKET: string;
	export const ca_dat_backup_bup_secrets__PGUSER: string;
	export const bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_PASSWORD: string;
	export const OCI_S3_SECRET_KEY: string;
	export const STARSHIP_SHELL: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_USER: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_ADMIN_EMAIL: string;
	export const SSH_S21_ED25519_PUB: string;
	export const NOCODB_API_TOKEN: string;
	export const vps_resend_secrets__cloudflare_api_token: string;
	export const NIX_SSL_CERT_FILE: string;
	export const ba_clo_cloudflare_secrets__cloudflare_api_key: string;
	export const OCI_SSH_KEY_FILE: string;
	export const SSH_SURFACE_PRO_ED25519_FILE: string;
	export const bc_obs_windmill_secrets__SMTP_PASSWORD: string;
	export const DEX2OATBOOTCLASSPATH: string;
	export const WG_OCI_ANALYTICS_PUBLIC_KEY: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_DB: string;
	export const aa_sui_mattermost_bots_secrets__MM_SQLSETTINGS_DATASOURCE: string;
	export const TMPDIR: string;
	export const bc_obs_dagu_secrets__DAGU_USERNAME: string;
	export const home_manager__shared_secrets__VAULT_ID_RSA: string;
	export const bc_obs_nocodb_secrets_powersheets__NC_ADMIN_PASSWORD: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_PASSWORD: string;
	export const aa_sui_tools_stalwart_secrets__ADMIN_PASSWORD: string;
	export const CF_API_KEY: string;
	export const NOCODB_URL: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_EMAIL: string;
	export const home_manager__shared_secrets__SURFACE_DEPLOY_PUB: string;
	export const AUTHELIA_OIDC_CREDENTIALS_DIR: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_HAIKU_SECRET: string;
	export const GCP_PROXY_SSH_KEY_PUB: string;
	export const aa_sui_tools_smtp_proxy_secrets__API_KEY: string;
	export const bc_obs_nocodb_secrets__POSTGRES_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_STORAGE_ENCRYPTION_KEY: string;
	export const ac_fin_crawlee_cloud_secrets__JWT_SECRET: string;
	export const aa_sui_tools_stalwart_secrets__AWS_RELAYUSER: string;
	export const vps_resend_secrets__resend_api_key: string;
	export const home_manager__shared_secrets__GCP_COMPUTE_ENGINE_PUB: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_SECRET: string;
	export const home_manager__shared_secrets__ID_ED25519: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_USER: string;
	export const bc_obs_c3_infra_mcp_secrets__CF_API_EMAIL: string;
	export const INIT_CWD: string;
	export const bc_obs_nocodb_secrets__NC_ADMIN_PASSWORD: string;
	export const home_manager__shared_secrets__VAULT_ID_RSA_PUB: string;
	export const STARSHIP_SESSION_KEY: string;
	export const aa_sui_mattermost_bots_secrets__MM_ADMIN_USERNAME: string;
	export const bc_obs_windmill_secrets__OAUTH_CLIENT_SECRET: string;
	export const ac_fin_crawlee_cloud_secrets__MINIO_PASSWORD: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_USER: string;
	export const WG_OCI_MAIL_PRIVATE_KEY: string;
	export const bc_obs_c3_services_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
	export const home_manager__shared_secrets__SURFACE_NIXOS_PUB: string;
	export const npm_lifecycle_script: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_PASSWORD: string;
	export const aa_sui_tools_stalwart_secrets__OCI_RELAYPASSWORD: string;
	export const ANDROID_DATA: string;
	export const ac_fin_crawlee_cloud_secrets__ADMIN_EMAIL: string;
	export const aa_sui_code_server_secrets__sudo_password: string;
	export const ab_mic_vaultwarden_secrets__SMTP_HOST: string;
	export const bc_obs_nocodb_secrets__NC_OIDC_CLIENT_SECRET: string;
	export const AGENT_SESSION_ID: string;
	export const TERMUX_APP__AM_SOCKET_SERVER_ENABLED: string;
	export const bc_obs_c3_infra_mcp_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_URL: string;
	export const npm_config_npm_version: string;
	export const ca_dat_backup_borg_secrets__BORG_PASSPHRASE: string;
	export const SHELL_CMD__SHELL_ID: string;
	export const WG_GCP_PROXY_PUBLIC_KEY: string;
	export const ac_fin_quant_lab_full_secrets__POSTGRES_USER: string;
	export const TERMUX_APP__SE_FILE_CONTEXT: string;
	export const ANDROID_STORAGE: string;
	export const CLOUDFLARE_API_KEY: string;
	export const aa_sui_snappymail_secrets__SNAPPYMAIL_ADMIN_PASSWORD: string;
	export const TERM: string;
	export const ab_mic_vaultwarden_secrets__SMTP_SECURITY: string;
	export const npm_package_name: string;
	export const bc_obs_c3_infra_api_secrets__DAGU_PASSWORD: string;
	export const TF_VAR_compartment_ocid: string;
	export const WG_SURFACE_PRIVATE_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_SESSION_SECRET: string;
	export const PROOT_L2S_DIR: string;
	export const SSH_SURFACE_PRO_ED25519_PUB: string;
	export const npm_config_prefix: string;
	export const OCI_API_KEY_PUB_FILE: string;
	export const bc_obs_umami_secrets__APP_SECRET: string;
	export const TERMUX_APP__IS_DEBUGGABLE_BUILD: string;
	export const USER: string;
	export const ab_mic_vaultwarden_secrets__SMTP_FROM: string;
	export const bc_obs_c3_services_mcp_secrets__GITHUB_TOKEN: string;
	export const OCI_S3_ACCESS_KEY: string;
	export const bb_sec_authelia_secrets__AUTHELIA_USER_DIEGO_HASH: string;
	export const aa_sui_photoprism_secrets__MARIADB_ROOT_PASSWORD: string;
	export const SOPS_AGE_KEY_FILE: string;
	export const ASEC_MOUNTPOINT: string;
	export const WG_GHA_RUNNER_PUBLIC_KEY: string;
	export const ac_fin_crawlee_cloud_secrets__MINIO_USER: string;
	export const TZDIR: string;
	export const aa_sui_tools_smtp_proxy_secrets__LISTEN_PORT: string;
	export const CF_ZONE_ID: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_JWKS_KEY: string;
	export const bc_obs_ntfy_secrets__NTFY_ADMIN_PASSWORD: string;
	export const ca_dat_backup_gitea_secrets__GITEA__security__INTERNAL_TOKEN: string;
	export const VISUAL: string;
	export const SSH_S21_ED25519_FILE: string;
	export const bc_obs_c3_infra_api_secrets__MM_BOT_TOKEN: string;
	export const AUTHELIA_TOKEN_URL: string;
	export const ANDROID_I18N_ROOT: string;
	export const bb_sec_caddy_secrets__CF_API_TOKEN: string;
	export const npm_lifecycle_event: string;
	export const SHLVL: string;
	export const ca_dat_backup_borg_secrets__ARCHIVE_NAME: string;
	export const ca_dat_backup_gitea_secrets__GITEA__oauth2__JWT_SECRET: string;
	export const ac_fin_crawlee_cloud_secrets__POSTGRES_PASSWORD: string;
	export const ca_dat_backup_bup_secrets__PGHOST: string;
	export const PAGER: string;
	export const ca_dat_db_agent_secrets__VM_NAME: string;
	export const home_manager__shared_secrets__CLAUDE_WEBSERVER_PUB: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUD_ADMIN_SECRET: string;
	export const bc_obs_dagu_secrets__AUTHELIA_OIDC_DAGU_SECRET: string;
	export const TF_VAR_cloudflare_api_key: string;
	export const ca_dat_backup_gitea_secrets__GITEA__security__SECRET_KEY: string;
	export const ac_fin_quant_lab_light_secrets__POSTGRES_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_CC_SECRET: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_ROOT_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MONITORING_SECRET: string;
	export const ANDROID_ROOT: string;
	export const NOCODB_XC_TOKEN: string;
	export const aa_sui_tools_smtp_proxy_secrets__SMTP_HOST: string;
	export const bc_obs_dagu_secrets__DAGU_PASSWORD: string;
	export const MIMALLOC_PAGE_RESET: string;
	export const ca_dat_backup_bup_secrets__MYSQL_PASSWORD: string;
	export const LOCALE_ARCHIVE: string;
	export const bb_sec_authelia_secrets__AUTHELIA_REDIS_PASSWORD: string;
	export const ATUIN_SESSION: string;
	export const MIMALLOC_LARGE_OS_PAGES: string;
	export const npm_config_user_agent: string;
	export const SHELL_CMD__TERMINAL_SESSION_NUMBER_SINCE_APP_START: string;
	export const BOOTCLASSPATH: string;
	export const aa_sui_photoprism_secrets__PHOTOPRISM_ADMIN_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_OPUS_SECRET: string;
	export const aa_sui_photoprism_secrets__MARIADB_DATABASE: string;
	export const aa_sui_code_server_secrets__CODE_SERVER_PASSWORD: string;
	export const npm_execpath: string;
	export const home_manager__shared_secrets__MATOMO_SERVER_PUB: string;
	export const bc_obs_windmill_secrets__SMTP_HOST: string;
	export const TERMUX_APP__APK_RELEASE: string;
	export const bc_obs_c3_infra_api_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
	export const bc_obs_umami_secrets__ADMIN_PASSWORD: string;
	export const CF_API_EMAIL: string;
	export const aa_sui_tools_stalwart_secrets__NOREPLY_PASSWORD: string;
	export const ad_agi_rig_agentic_hai_1_5bq4_secrets__MM_BOT_TOKEN: string;
	export const aa_sui_tools_stalwart_secrets__ME_PASSWORD: string;
	export const bc_obs_c3_infra_mcp_secrets__CF_API_KEY: string;
	export const XDG_RUNTIME_DIR: string;
	export const bc_obs_windmill_secrets__OAUTH_CLIENT_ID: string;
	export const aa_sui_tools_stalwart_secrets__OCI_RELAYUSER: string;
	export const GCP_T4_SSH_KEY_PUB: string;
	export const aa_sui_mattermost_bots_secrets__BEARER_TOKEN: string;
	export const NODE_PATH: string;
	export const TERMUX_APP__VERSION_CODE: string;
	export const CF_DOMAIN: string;
	export const AUTHELIA_OIDC_TOKENS_DIR: string;
	export const npm_package_json: string;
	export const aa_sui_mail_mcp_secrets__RESEND_API_KEY: string;
	export const bc_obs_nocodb_secrets__NC_AUTH_JWT_SECRET: string;
	export const ANDROID_TZDATA_ROOT: string;
	export const bc_obs_c3_infra_api_secrets__RESEND_API_KEY: string;
	export const bc_obs_c3_infra_mcp_secrets__DAGU_USERNAME: string;
	export const bc_obs_dagu_secrets__BORG_PASSPHRASE: string;
	export const LC_ALL: string;
	export const OCI_SSH_KEY_PUB: string;
	export const SHELL_CMD__PACKAGE_NAME: string;
	export const WG_SURFACE_PUBLIC_KEY: string;
	export const bc_obs_c3_infra_api_secrets__CF_API_EMAIL: string;
	export const aa_sui_tools_smtp_proxy_secrets__SMTP_PORT: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NPM_SECRET: string;
	export const npm_config_noproxy: string;
	export const PATH: string;
	export const npm_config_node_gyp: string;
	export const ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_URL: string;
	export const __NOD_SESS_INIT_SOURCED: string;
	export const bb_sec_authelia_secrets__AUTHELIA_SMTP_PASSWORD: string;
	export const FZF_DEFAULT_OPTS: string;
	export const bc_obs_dagu_secrets__RESTIC_PASSWORD: string;
	export const npm_config_global_prefix: string;
	export const bc_obs_matomo_secrets__MATOMO_DB_NAME: string;
	export const ANDROID_ART_ROOT: string;
	export const TERMUX_APP__TARGET_SDK: string;
	export const aa_sui_mattermost_bots_secrets__POSTGRES_PASSWORD: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLI_SECRET: string;
	export const OCI_FINGERPRINT: string;
	export const aa_sui_mail_mcp_secrets__STALWART_ADMIN_USER: string;
	export const bb_sec_authelia_secrets__AUTHELIA_OIDC_HMAC_SECRET: string;
	export const TF_VAR_region: string;
	export const GOOSE_DISABLE_KEYRING: string;
	export const aa_sui_mail_mcp_secrets__MAIL_USER: string;
	export const ANDROID_ASSETS: string;
	export const npm_node_execpath: string;
	export const WG_TERMUX_PUBLIC_KEY: string;
	export const bc_obs_windmill_secrets__SMTP_FROM: string;
	export const bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_USER: string;
	export const GOOSE_TMP: string;
	export const OLDPWD: string;
	export const CF_API_TOKEN: string;
	export const NODE_ENV: string;
}

/**
 * Similar to [`$env/static/private`](https://svelte.dev/docs/kit/$env-static-private), except that it only includes environment variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Values are replaced statically at build time.
 * 
 * ```ts
 * import { PUBLIC_BASE_URL } from '$env/static/public';
 * ```
 */
declare module '$env/static/public' {
	
}

/**
 * This module provides access to runtime environment variables, as defined by the platform you're running on. For example if you're using [`adapter-node`](https://github.com/sveltejs/kit/tree/main/packages/adapter-node) (or running [`vite preview`](https://svelte.dev/docs/kit/cli)), this is equivalent to `process.env`. This module only includes variables that _do not_ begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) _and do_ start with [`config.kit.env.privatePrefix`](https://svelte.dev/docs/kit/configuration#env) (if configured).
 * 
 * This module cannot be imported into client-side code.
 * 
 * ```ts
 * import { env } from '$env/dynamic/private';
 * console.log(env.DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 * 
 * > [!NOTE] In `dev`, `$env/dynamic` always includes environment variables from `.env`. In `prod`, this behavior will depend on your adapter.
 */
declare module '$env/dynamic/private' {
	export const env: {
		SHELL: string;
		npm_command: string;
		aa_sui_radicale_secrets__RADICALE_USERS: string;
		bc_obs_ntfy_secrets__NTFY_USER_PASSWORD: string;
		SSH_S21_RSA_PUB: string;
		bc_obs_c3_infra_api_secrets__CF_API_KEY: string;
		ca_dat_db_agent_secrets__NTFY_URL: string;
		npm_config_userconfig: string;
		bc_obs_nocodb_secrets__NC_ADMIN_EMAIL: string;
		COLORTERM: string;
		VAULT_DEPLOY_KEY_FILE: string;
		__HM_SESS_VARS_SOURCED: string;
		bc_obs_dagu_secrets__OCI_S3_SECRET_KEY: string;
		aa_sui_tools_stalwart_secrets__DKIM_PRIVATE_KEY_B64: string;
		SSH_S21_RSA_FILE: string;
		aa_sui_mattermost_bots_secrets__MM_CLAUDE_PASSWORD: string;
		RESEND_API_KEY: string;
		npm_config_cache: string;
		aa_sui_mattermost_mcp_secrets__MM_ADMIN_USERNAME: string;
		LESS: string;
		CRAWLEE_API_TOKEN: string;
		ca_dat_backup_bup_secrets__MYSQL_USER: string;
		DTK_NODE_NAME: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_CC_SECRET: string;
		AUTHELIA_OIDC_CLIENT_ID: string;
		aa_sui_google_workspace_mcp_secrets__GOOGLE_SERVICE_ACCOUNT_KEY: string;
		WIREGUARD_PUBLIC_IP: string;
		TERMUX_APP__USER_ID: string;
		WG_PRIVATE_KEY: string;
		ca_dat_backup_bup_secrets__MYSQL_HOST: string;
		aa_sui_mattermost_mcp_secrets__MM_CLAUDE_PASSWORD: string;
		OCI_S3_REGION: string;
		bc_obs_windmill_secrets__SMTP_USERNAME: string;
		bc_obs_windmill_secrets__SMTP_PORT: string;
		NOCODB_ADMIN_EMAIL: string;
		bc_obs_nocodb_secrets_powersheets__POSTGRES_PASSWORD: string;
		vps_resend_secrets__cloudflare_zone_id: string;
		AUTHELIA_JWKS_PUBLIC_KEY_FILE: string;
		PREFIX: string;
		aa_sui_mattermost_mcp_secrets__MM_URL: string;
		OCI_USER_OCID: string;
		NODE: string;
		ab_mic_vaultwarden_secrets__SMTP_PASSWORD: string;
		ca_dat_backup_bup_secrets__PGPASSWORD: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_DB: string;
		bc_obs_matomo_secrets__MYSQL_ROOT_PASSWORD: string;
		TERMUX_APP__UID: string;
		bc_obs_c3_services_mcp_secrets__DAGU_BASIC_AUTH: string;
		ca_dat_backup_bup_secrets__SQLITE_DBS: string;
		OCI_API_KEY_FILE: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MATTERMOST_SECRET: string;
		CLOUDFLARE_EMAIL: string;
		ANTHROPIC_API_KEY: string;
		SHELL_CMD__RUNNER_NAME: string;
		MALLOC_ARENA_MAX: string;
		TERMUX_APP__PACKAGE_NAME: string;
		C3_API_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SECRET: string;
		WG_GCP_PROXY_PRIVATE_KEY: string;
		bb_sec_caddy_secrets__AUTHELIA_CLI_SECRET: string;
		aa_sui_photoprism_secrets__MARIADB_USER: string;
		ac_fin_crawlee_cloud_secrets__RUNNER_TOKEN: string;
		GCP_PROXY_SSH_KEY_FILE: string;
		aa_sui_mail_mcp_secrets__MAIL_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUDFLARE_SECRET: string;
		bc_obs_windmill_secrets__DB_PASSWORD: string;
		aa_sui_photoprism_secrets__MARIADB_PASSWORD: string;
		bc_obs_c3_infra_mcp_secrets__C3_API_KEY: string;
		bc_obs_nocodb_secrets_powersheets__NC_AUTH_JWT_SECRET: string;
		TERMUX_APP__SE_PROCESS_CONTEXT: string;
		TERMUX_APP__VERSION_NAME: string;
		COLOR: string;
		OPENAI_API_KEY: string;
		TERMUX_APP__APK_PATH: string;
		LOCALE_ARCHIVE_2_27: string;
		npm_config_local_prefix: string;
		WG_OCI_APPS_PRIVATE_KEY: string;
		AUTHELIA_JWKS_PRIVATE_KEY_FILE: string;
		GPG_PUBLIC_KEY_FILE: string;
		bb_sec_authelia_secrets__AUTHELIA_JWT_SECRET: string;
		aa_sui_mattermost_bots_secrets__AUTHELIA_OIDC_MATTERMOST_SECRET: string;
		ca_dat_backup_bup_secrets__MYSQL_DBS: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_PASSWORD: string;
		ca_dat_db_agent_secrets__BUP_REMOTE: string;
		npm_config_globalconfig: string;
		TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE: string;
		EDITOR: string;
		aa_sui_tools_stalwart_secrets__CF_DNS_API_TOKEN: string;
		ca_dat_db_agent_secrets__NTFY_TOPIC: string;
		TERMUX_APP__PACKAGE_VARIANT: string;
		ab_mic_vaultwarden_secrets__SMTP_USERNAME: string;
		bc_obs_umami_secrets__DB_PASSWORD: string;
		aa_sui_photoprism_secrets__OCI_S3_ACCESS_KEY: string;
		bc_obs_c3_infra_mcp_secrets__RESEND_API_KEY: string;
		OCI_REGION: string;
		OPENAI_BASE_URL: string;
		PWD: string;
		NIX_PROFILES: string;
		aa_sui_photoprism_secrets__OCI_S3_SECRET_KEY: string;
		PROOT_TMP_DIR: string;
		WIREGUARD_IP: string;
		ca_dat_backup_bup_secrets__POSTGRES_DBS: string;
		TF_VAR_tenancy_ocid: string;
		WG_OCI_APPS_PUBLIC_KEY: string;
		ca_dat_kg_graph_secrets__SURREAL_ROOT_PASSWORD: string;
		NIX_PATH: string;
		home_manager__shared_secrets__GCP_COMPUTE_ENGINE: string;
		npm_config_init_module: string;
		TERMUX_APP__FILES_DIR: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__MM_BOT_TOKEN: string;
		GCP_SERVICE_ACCOUNT_KEY_FILE: string;
		_: string;
		ca_dat_redis_secrets__REDIS_PASSWORD: string;
		aa_sui_mattermost_mcp_secrets__CLAUDE_MODEL: string;
		ab_mic_vaultwarden_secrets__ADMIN_TOKEN: string;
		GPG_PRIVATE_KEY_FILE: string;
		bc_obs_c3_infra_mcp_secrets__DAGU_PASSWORD: string;
		WG_OCI_ANALYTICS_PRIVATE_KEY: string;
		TERMUX_VERSION: string;
		WG_TERMUX_PRIVATE_KEY: string;
		TF_PLUGIN_CACHE_DIR: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_DB: string;
		bc_obs_c3_infra_api_secrets__C3_API_KEY: string;
		bc_obs_c3_infra_mcp_secrets__MM_BOT_TOKEN: string;
		OCI_S3_ENDPOINT: string;
		ca_dat_backup_borg_secrets__SOURCE_DIRS: string;
		TERMUX_APP__SE_INFO: string;
		ac_fin_crawlee_cloud_secrets__ADMIN_PASSWORD: string;
		OCI_TENANCY_OCID: string;
		aa_sui_mattermost_mcp_secrets__MM_TEAM_ID: string;
		SYSTEMSERVERCLASSPATH: string;
		EXTERNAL_STORAGE: string;
		LD_PRELOAD: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
		ab_mic_vaultwarden_secrets__SMTP_PORT: string;
		bc_obs_c3_infra_api_secrets__DAGU_USERNAME: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NOCODB_SECRET: string;
		HOME: string;
		WG_OCI_MAIL_PUBLIC_KEY: string;
		GCP_T4_SSH_KEY_FILE: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_SONNET_SECRET: string;
		LANG: string;
		bb_sec_caddy_secrets__NTFY_ADMIN_AUTH: string;
		SHELL_CMD__TERMINAL_SESSION_NUMBER_SINCE_BOOT: string;
		TERMUX_APP__PID: string;
		GITHUB_TOKEN: string;
		TMUX_TMPDIR: string;
		aa_sui_tools_stalwart_secrets__AWS_RELAYPASSWORD: string;
		TERMUX_APP__PACKAGE_MANAGER: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_C3_MCP_SECRET: string;
		GC_NPROCS: string;
		bc_obs_umami_secrets__ADMIN_USERNAME: string;
		OCI_S3_BUCKET: string;
		ca_dat_backup_bup_secrets__PGUSER: string;
		bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_PASSWORD: string;
		OCI_S3_SECRET_KEY: string;
		STARSHIP_SHELL: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_USER: string;
		bc_obs_nocodb_secrets_powersheets__NC_ADMIN_EMAIL: string;
		SSH_S21_ED25519_PUB: string;
		NOCODB_API_TOKEN: string;
		vps_resend_secrets__cloudflare_api_token: string;
		NIX_SSL_CERT_FILE: string;
		ba_clo_cloudflare_secrets__cloudflare_api_key: string;
		OCI_SSH_KEY_FILE: string;
		SSH_SURFACE_PRO_ED25519_FILE: string;
		bc_obs_windmill_secrets__SMTP_PASSWORD: string;
		DEX2OATBOOTCLASSPATH: string;
		WG_OCI_ANALYTICS_PUBLIC_KEY: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_DB: string;
		aa_sui_mattermost_bots_secrets__MM_SQLSETTINGS_DATASOURCE: string;
		TMPDIR: string;
		bc_obs_dagu_secrets__DAGU_USERNAME: string;
		home_manager__shared_secrets__VAULT_ID_RSA: string;
		bc_obs_nocodb_secrets_powersheets__NC_ADMIN_PASSWORD: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_PASSWORD: string;
		aa_sui_tools_stalwart_secrets__ADMIN_PASSWORD: string;
		CF_API_KEY: string;
		NOCODB_URL: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_EMAIL: string;
		home_manager__shared_secrets__SURFACE_DEPLOY_PUB: string;
		AUTHELIA_OIDC_CREDENTIALS_DIR: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_HAIKU_SECRET: string;
		GCP_PROXY_SSH_KEY_PUB: string;
		aa_sui_tools_smtp_proxy_secrets__API_KEY: string;
		bc_obs_nocodb_secrets__POSTGRES_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_STORAGE_ENCRYPTION_KEY: string;
		ac_fin_crawlee_cloud_secrets__JWT_SECRET: string;
		aa_sui_tools_stalwart_secrets__AWS_RELAYUSER: string;
		vps_resend_secrets__resend_api_key: string;
		home_manager__shared_secrets__GCP_COMPUTE_ENGINE_PUB: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_SECRET: string;
		home_manager__shared_secrets__ID_ED25519: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_USER: string;
		bc_obs_c3_infra_mcp_secrets__CF_API_EMAIL: string;
		INIT_CWD: string;
		bc_obs_nocodb_secrets__NC_ADMIN_PASSWORD: string;
		home_manager__shared_secrets__VAULT_ID_RSA_PUB: string;
		STARSHIP_SESSION_KEY: string;
		aa_sui_mattermost_bots_secrets__MM_ADMIN_USERNAME: string;
		bc_obs_windmill_secrets__OAUTH_CLIENT_SECRET: string;
		ac_fin_crawlee_cloud_secrets__MINIO_PASSWORD: string;
		bc_obs_matomo_secrets__MATOMO_DB_USER: string;
		WG_OCI_MAIL_PRIVATE_KEY: string;
		bc_obs_c3_services_mcp_secrets__STALWART_ADMIN_PASSWORD: string;
		home_manager__shared_secrets__SURFACE_NIXOS_PUB: string;
		npm_lifecycle_script: string;
		bc_obs_matomo_secrets__MATOMO_DB_PASSWORD: string;
		aa_sui_tools_stalwart_secrets__OCI_RELAYPASSWORD: string;
		ANDROID_DATA: string;
		ac_fin_crawlee_cloud_secrets__ADMIN_EMAIL: string;
		aa_sui_code_server_secrets__sudo_password: string;
		ab_mic_vaultwarden_secrets__SMTP_HOST: string;
		bc_obs_nocodb_secrets__NC_OIDC_CLIENT_SECRET: string;
		AGENT_SESSION_ID: string;
		TERMUX_APP__AM_SOCKET_SERVER_ENABLED: string;
		bc_obs_c3_infra_mcp_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_URL: string;
		npm_config_npm_version: string;
		ca_dat_backup_borg_secrets__BORG_PASSPHRASE: string;
		SHELL_CMD__SHELL_ID: string;
		WG_GCP_PROXY_PUBLIC_KEY: string;
		ac_fin_quant_lab_full_secrets__POSTGRES_USER: string;
		TERMUX_APP__SE_FILE_CONTEXT: string;
		ANDROID_STORAGE: string;
		CLOUDFLARE_API_KEY: string;
		aa_sui_snappymail_secrets__SNAPPYMAIL_ADMIN_PASSWORD: string;
		TERM: string;
		ab_mic_vaultwarden_secrets__SMTP_SECURITY: string;
		npm_package_name: string;
		bc_obs_c3_infra_api_secrets__DAGU_PASSWORD: string;
		TF_VAR_compartment_ocid: string;
		WG_SURFACE_PRIVATE_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_SESSION_SECRET: string;
		PROOT_L2S_DIR: string;
		SSH_SURFACE_PRO_ED25519_PUB: string;
		npm_config_prefix: string;
		OCI_API_KEY_PUB_FILE: string;
		bc_obs_umami_secrets__APP_SECRET: string;
		TERMUX_APP__IS_DEBUGGABLE_BUILD: string;
		USER: string;
		ab_mic_vaultwarden_secrets__SMTP_FROM: string;
		bc_obs_c3_services_mcp_secrets__GITHUB_TOKEN: string;
		OCI_S3_ACCESS_KEY: string;
		bb_sec_authelia_secrets__AUTHELIA_USER_DIEGO_HASH: string;
		aa_sui_photoprism_secrets__MARIADB_ROOT_PASSWORD: string;
		SOPS_AGE_KEY_FILE: string;
		ASEC_MOUNTPOINT: string;
		WG_GHA_RUNNER_PUBLIC_KEY: string;
		ac_fin_crawlee_cloud_secrets__MINIO_USER: string;
		TZDIR: string;
		aa_sui_tools_smtp_proxy_secrets__LISTEN_PORT: string;
		CF_ZONE_ID: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_JWKS_KEY: string;
		bc_obs_ntfy_secrets__NTFY_ADMIN_PASSWORD: string;
		ca_dat_backup_gitea_secrets__GITEA__security__INTERNAL_TOKEN: string;
		VISUAL: string;
		SSH_S21_ED25519_FILE: string;
		bc_obs_c3_infra_api_secrets__MM_BOT_TOKEN: string;
		AUTHELIA_TOKEN_URL: string;
		ANDROID_I18N_ROOT: string;
		bb_sec_caddy_secrets__CF_API_TOKEN: string;
		npm_lifecycle_event: string;
		SHLVL: string;
		ca_dat_backup_borg_secrets__ARCHIVE_NAME: string;
		ca_dat_backup_gitea_secrets__GITEA__oauth2__JWT_SECRET: string;
		ac_fin_crawlee_cloud_secrets__POSTGRES_PASSWORD: string;
		ca_dat_backup_bup_secrets__PGHOST: string;
		PAGER: string;
		ca_dat_db_agent_secrets__VM_NAME: string;
		home_manager__shared_secrets__CLAUDE_WEBSERVER_PUB: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLOUD_ADMIN_SECRET: string;
		bc_obs_dagu_secrets__AUTHELIA_OIDC_DAGU_SECRET: string;
		TF_VAR_cloudflare_api_key: string;
		ca_dat_backup_gitea_secrets__GITEA__security__SECRET_KEY: string;
		ac_fin_quant_lab_light_secrets__POSTGRES_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_DAGU_CC_SECRET: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_ROOT_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_MONITORING_SECRET: string;
		ANDROID_ROOT: string;
		NOCODB_XC_TOKEN: string;
		aa_sui_tools_smtp_proxy_secrets__SMTP_HOST: string;
		bc_obs_dagu_secrets__DAGU_PASSWORD: string;
		MIMALLOC_PAGE_RESET: string;
		ca_dat_backup_bup_secrets__MYSQL_PASSWORD: string;
		LOCALE_ARCHIVE: string;
		bb_sec_authelia_secrets__AUTHELIA_REDIS_PASSWORD: string;
		ATUIN_SESSION: string;
		MIMALLOC_LARGE_OS_PAGES: string;
		npm_config_user_agent: string;
		SHELL_CMD__TERMINAL_SESSION_NUMBER_SINCE_APP_START: string;
		BOOTCLASSPATH: string;
		aa_sui_photoprism_secrets__PHOTOPRISM_ADMIN_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLAUDE_OPUS_SECRET: string;
		aa_sui_photoprism_secrets__MARIADB_DATABASE: string;
		aa_sui_code_server_secrets__CODE_SERVER_PASSWORD: string;
		npm_execpath: string;
		home_manager__shared_secrets__MATOMO_SERVER_PUB: string;
		bc_obs_windmill_secrets__SMTP_HOST: string;
		TERMUX_APP__APK_RELEASE: string;
		bc_obs_c3_infra_api_secrets__AUTHELIA_OIDC_C3_MCP_SECRET: string;
		bc_obs_umami_secrets__ADMIN_PASSWORD: string;
		CF_API_EMAIL: string;
		aa_sui_tools_stalwart_secrets__NOREPLY_PASSWORD: string;
		ad_agi_rig_agentic_hai_1_5bq4_secrets__MM_BOT_TOKEN: string;
		aa_sui_tools_stalwart_secrets__ME_PASSWORD: string;
		bc_obs_c3_infra_mcp_secrets__CF_API_KEY: string;
		XDG_RUNTIME_DIR: string;
		bc_obs_windmill_secrets__OAUTH_CLIENT_ID: string;
		aa_sui_tools_stalwart_secrets__OCI_RELAYUSER: string;
		GCP_T4_SSH_KEY_PUB: string;
		aa_sui_mattermost_bots_secrets__BEARER_TOKEN: string;
		NODE_PATH: string;
		TERMUX_APP__VERSION_CODE: string;
		CF_DOMAIN: string;
		AUTHELIA_OIDC_TOKENS_DIR: string;
		npm_package_json: string;
		aa_sui_mail_mcp_secrets__RESEND_API_KEY: string;
		bc_obs_nocodb_secrets__NC_AUTH_JWT_SECRET: string;
		ANDROID_TZDATA_ROOT: string;
		bc_obs_c3_infra_api_secrets__RESEND_API_KEY: string;
		bc_obs_c3_infra_mcp_secrets__DAGU_USERNAME: string;
		bc_obs_dagu_secrets__BORG_PASSPHRASE: string;
		LC_ALL: string;
		OCI_SSH_KEY_PUB: string;
		SHELL_CMD__PACKAGE_NAME: string;
		WG_SURFACE_PUBLIC_KEY: string;
		bc_obs_c3_infra_api_secrets__CF_API_EMAIL: string;
		aa_sui_tools_smtp_proxy_secrets__SMTP_PORT: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_NPM_SECRET: string;
		npm_config_noproxy: string;
		PATH: string;
		npm_config_node_gyp: string;
		ad_agi_rig_agentic_sonn_14bq8_secrets__SURREAL_URL: string;
		__NOD_SESS_INIT_SOURCED: string;
		bb_sec_authelia_secrets__AUTHELIA_SMTP_PASSWORD: string;
		FZF_DEFAULT_OPTS: string;
		bc_obs_dagu_secrets__RESTIC_PASSWORD: string;
		npm_config_global_prefix: string;
		bc_obs_matomo_secrets__MATOMO_DB_NAME: string;
		ANDROID_ART_ROOT: string;
		TERMUX_APP__TARGET_SDK: string;
		aa_sui_mattermost_bots_secrets__POSTGRES_PASSWORD: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_CLIENT_CLI_SECRET: string;
		OCI_FINGERPRINT: string;
		aa_sui_mail_mcp_secrets__STALWART_ADMIN_USER: string;
		bb_sec_authelia_secrets__AUTHELIA_OIDC_HMAC_SECRET: string;
		TF_VAR_region: string;
		GOOSE_DISABLE_KEYRING: string;
		aa_sui_mail_mcp_secrets__MAIL_USER: string;
		ANDROID_ASSETS: string;
		npm_node_execpath: string;
		WG_TERMUX_PUBLIC_KEY: string;
		bc_obs_windmill_secrets__SMTP_FROM: string;
		bc_obs_lgtm_secrets__GF_SECURITY_ADMIN_USER: string;
		GOOSE_TMP: string;
		OLDPWD: string;
		CF_API_TOKEN: string;
		NODE_ENV: string;
		[key: `PUBLIC_${string}`]: undefined;
		[key: `${string}`]: string | undefined;
	}
}

/**
 * Similar to [`$env/dynamic/private`](https://svelte.dev/docs/kit/$env-dynamic-private), but only includes variables that begin with [`config.kit.env.publicPrefix`](https://svelte.dev/docs/kit/configuration#env) (which defaults to `PUBLIC_`), and can therefore safely be exposed to client-side code.
 * 
 * Note that public dynamic environment variables must all be sent from the server to the client, causing larger network requests — when possible, use `$env/static/public` instead.
 * 
 * ```ts
 * import { env } from '$env/dynamic/public';
 * console.log(env.PUBLIC_DEPLOYMENT_SPECIFIC_VARIABLE);
 * ```
 */
declare module '$env/dynamic/public' {
	export const env: {
		[key: `PUBLIC_${string}`]: string | undefined;
	}
}
