/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/common/ActionBar.vue')['default']
    ArticleCard: typeof import('./components/features/cards/ArticleCard.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    ContentHeader: typeof import('./components/common/ContentHeader.vue')['default']
    FeedContainer: typeof import('./components/features/feed/FeedContainer.vue')['default']
    GitHubRow: typeof import('./components/myfeed/GitHubRow.vue')['default']
    GlassCard: typeof import('./components/common/GlassCard.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    MarkdownCard: typeof import('./components/features/cards/MarkdownCard.vue')['default']
    MusicRow: typeof import('./components/myfeed/MusicRow.vue')['default']
    MyFeedContainer: typeof import('./components/myfeed/MyFeedContainer.vue')['default']
    NewsFeedContainer: typeof import('./components/newsfeed/NewsFeedContainer.vue')['default']
    NewsRow: typeof import('./components/newsfeed/NewsRow.vue')['default']
    RSSCard: typeof import('./components/features/cards/RSSCard.vue')['default']
    RssSidebar: typeof import('./components/features/feed/RssSidebar.vue')['default']
    SkeletonCard: typeof import('./components/common/SkeletonCard.vue')['default']
    TabBar: typeof import('./components/common/TabBar.vue')['default']
    TidalCard: typeof import('./components/features/cards/TidalCard.vue')['default']
    TweetCard: typeof import('./components/features/cards/TweetCard.vue')['default']
    UserComment: typeof import('./components/common/UserComment.vue')['default']
    VideoRow: typeof import('./components/myfeed/VideoRow.vue')['default']
    YouTubeCard: typeof import('./components/features/cards/YouTubeCard.vue')['default']
  }
}
