// Auto-generated by export_cloud_control_data.py
// Generated: 2025-12-14T10:48:05.724329
// Endpoint: /api/cloud_control/costs_infra

const COSTS_INFRA = {
  "costs": {
    "oracle": {
      "name": "Oracle Cloud",
      "tier": "always-free",
      "monthly": 0,
      "paidVms": {
        "oci-p-flex_1": {
          "monthly": 5.5,
          "hourly": 0.037
        }
      },
      "resources": {
        "vms": "2x E2.1.Micro (free) + 1x A1.Flex (free, pending) + 1x E4.Flex (paid)",
        "storage": "200GB block",
        "bandwidth": "10TB egress"
      }
    },
    "gcloud": {
      "name": "Google Cloud",
      "tier": "free-tier",
      "monthly": 0,
      "resources": {
        "vms": "1x e2-micro",
        "storage": "30GB standard",
        "bandwidth": "1GB egress"
      }
    },
    "cloudflare": {
      "name": "Cloudflare",
      "tier": "free",
      "monthly": 0
    },
    "letsencrypt": {
      "name": "Let's Encrypt",
      "tier": "free",
      "monthly": 0
    },
    "squarespace": {
      "name": "Squarespace",
      "tier": "paid",
      "monthly": 16,
      "notes": "cloud.diegonmarcos.com hosting"
    }
  },
  "timestamp": "2025-12-07"
};

// For ES6 modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = COSTS_INFRA;
}
